<?php
/**
 * BillOfLading
 *
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Infoplus\Model;

use \ArrayAccess;
/**
 * BillOfLading Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Infoplus
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BillOfLading implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'id' => 'int',
        'create_date' => '\DateTime',
        'modify_date' => '\DateTime',
        'lob_id' => 'int',
        'order_no' => 'Number',
        'bol_no' => 'string',
        'bol_date' => '\DateTime',
        'ship_from_name' => 'string',
        'ship_from_attention' => 'string',
        'ship_from_address' => 'string',
        'ship_from_city' => 'string',
        'ship_from_state' => 'string',
        'ship_from_zip' => 'string',
        'ship_from_country' => 'string',
        'sid' => 'string',
        'is_ship_from_fob' => 'bool',
        'ship_to_name' => 'string',
        'ship_to_attention' => 'string',
        'ship_to_address' => 'string',
        'ship_to_city' => 'string',
        'ship_to_state' => 'string',
        'ship_to_zip' => 'string',
        'ship_to_country' => 'string',
        'ship_to_location_no' => 'string',
        'cid' => 'string',
        'is_ship_to_fob' => 'bool',
        'bill_to_name' => 'string',
        'bill_to_attention' => 'string',
        'bill_to_address' => 'string',
        'bill_to_city' => 'string',
        'bill_to_state' => 'string',
        'bill_to_zip' => 'string',
        'bill_to_country' => 'string',
        'is_trailer_loaded_by_shipper' => 'bool',
        'by_driver' => 'bool',
        'cod_amount' => 'Number',
        'fee_terms_collect' => 'bool',
        'fee_terms_prepaid' => 'bool',
        'customer_check_acceptable' => 'bool',
        'carrier_name' => 'string',
        'trailer_no' => 'string',
        'seal_no' => 'string',
        'scac' => 'string',
        'pro_no' => 'string',
        'prepaid' => 'bool',
        'collect' => 'bool',
        'third_party' => 'bool',
        'is_this_a_master_bol' => 'bool',
        'master_bol_id' => 'int',
        'is_freight_counted_by_shipper' => 'bool',
        'by_driver_pallets' => 'bool',
        'by_driver_pieces' => 'bool',
        'special_instructions' => 'string',
        'order_info_lines' => '\Infoplus\Model\BillOfLadingOrderInfoLine[]',
        'carrier_info_lines' => '\Infoplus\Model\BillOfLadingCarrierInfoLine[]',
        'custom_fields' => 'map[string,object]'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'id' => 'id',
        'create_date' => 'createDate',
        'modify_date' => 'modifyDate',
        'lob_id' => 'lobId',
        'order_no' => 'orderNo',
        'bol_no' => 'bolNo',
        'bol_date' => 'bolDate',
        'ship_from_name' => 'shipFromName',
        'ship_from_attention' => 'shipFromAttention',
        'ship_from_address' => 'shipFromAddress',
        'ship_from_city' => 'shipFromCity',
        'ship_from_state' => 'shipFromState',
        'ship_from_zip' => 'shipFromZip',
        'ship_from_country' => 'shipFromCountry',
        'sid' => 'sid',
        'is_ship_from_fob' => 'isShipFromFOB',
        'ship_to_name' => 'shipToName',
        'ship_to_attention' => 'shipToAttention',
        'ship_to_address' => 'shipToAddress',
        'ship_to_city' => 'shipToCity',
        'ship_to_state' => 'shipToState',
        'ship_to_zip' => 'shipToZip',
        'ship_to_country' => 'shipToCountry',
        'ship_to_location_no' => 'shipToLocationNo',
        'cid' => 'cid',
        'is_ship_to_fob' => 'isShipToFOB',
        'bill_to_name' => 'billToName',
        'bill_to_attention' => 'billToAttention',
        'bill_to_address' => 'billToAddress',
        'bill_to_city' => 'billToCity',
        'bill_to_state' => 'billToState',
        'bill_to_zip' => 'billToZip',
        'bill_to_country' => 'billToCountry',
        'is_trailer_loaded_by_shipper' => 'isTrailerLoadedByShipper',
        'by_driver' => 'byDriver',
        'cod_amount' => 'codAmount',
        'fee_terms_collect' => 'feeTermsCollect',
        'fee_terms_prepaid' => 'feeTermsPrepaid',
        'customer_check_acceptable' => 'customerCheckAcceptable',
        'carrier_name' => 'carrierName',
        'trailer_no' => 'trailerNo',
        'seal_no' => 'sealNo',
        'scac' => 'scac',
        'pro_no' => 'proNo',
        'prepaid' => 'prepaid',
        'collect' => 'collect',
        'third_party' => 'thirdParty',
        'is_this_a_master_bol' => 'isThisAMasterBOL',
        'master_bol_id' => 'masterBOLId',
        'is_freight_counted_by_shipper' => 'isFreightCountedByShipper',
        'by_driver_pallets' => 'byDriverPallets',
        'by_driver_pieces' => 'byDriverPieces',
        'special_instructions' => 'specialInstructions',
        'order_info_lines' => 'orderInfoLines',
        'carrier_info_lines' => 'carrierInfoLines',
        'custom_fields' => 'customFields'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'id' => 'setId',
        'create_date' => 'setCreateDate',
        'modify_date' => 'setModifyDate',
        'lob_id' => 'setLobId',
        'order_no' => 'setOrderNo',
        'bol_no' => 'setBolNo',
        'bol_date' => 'setBolDate',
        'ship_from_name' => 'setShipFromName',
        'ship_from_attention' => 'setShipFromAttention',
        'ship_from_address' => 'setShipFromAddress',
        'ship_from_city' => 'setShipFromCity',
        'ship_from_state' => 'setShipFromState',
        'ship_from_zip' => 'setShipFromZip',
        'ship_from_country' => 'setShipFromCountry',
        'sid' => 'setSid',
        'is_ship_from_fob' => 'setIsShipFromFob',
        'ship_to_name' => 'setShipToName',
        'ship_to_attention' => 'setShipToAttention',
        'ship_to_address' => 'setShipToAddress',
        'ship_to_city' => 'setShipToCity',
        'ship_to_state' => 'setShipToState',
        'ship_to_zip' => 'setShipToZip',
        'ship_to_country' => 'setShipToCountry',
        'ship_to_location_no' => 'setShipToLocationNo',
        'cid' => 'setCid',
        'is_ship_to_fob' => 'setIsShipToFob',
        'bill_to_name' => 'setBillToName',
        'bill_to_attention' => 'setBillToAttention',
        'bill_to_address' => 'setBillToAddress',
        'bill_to_city' => 'setBillToCity',
        'bill_to_state' => 'setBillToState',
        'bill_to_zip' => 'setBillToZip',
        'bill_to_country' => 'setBillToCountry',
        'is_trailer_loaded_by_shipper' => 'setIsTrailerLoadedByShipper',
        'by_driver' => 'setByDriver',
        'cod_amount' => 'setCodAmount',
        'fee_terms_collect' => 'setFeeTermsCollect',
        'fee_terms_prepaid' => 'setFeeTermsPrepaid',
        'customer_check_acceptable' => 'setCustomerCheckAcceptable',
        'carrier_name' => 'setCarrierName',
        'trailer_no' => 'setTrailerNo',
        'seal_no' => 'setSealNo',
        'scac' => 'setScac',
        'pro_no' => 'setProNo',
        'prepaid' => 'setPrepaid',
        'collect' => 'setCollect',
        'third_party' => 'setThirdParty',
        'is_this_a_master_bol' => 'setIsThisAMasterBol',
        'master_bol_id' => 'setMasterBolId',
        'is_freight_counted_by_shipper' => 'setIsFreightCountedByShipper',
        'by_driver_pallets' => 'setByDriverPallets',
        'by_driver_pieces' => 'setByDriverPieces',
        'special_instructions' => 'setSpecialInstructions',
        'order_info_lines' => 'setOrderInfoLines',
        'carrier_info_lines' => 'setCarrierInfoLines',
        'custom_fields' => 'setCustomFields'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'id' => 'getId',
        'create_date' => 'getCreateDate',
        'modify_date' => 'getModifyDate',
        'lob_id' => 'getLobId',
        'order_no' => 'getOrderNo',
        'bol_no' => 'getBolNo',
        'bol_date' => 'getBolDate',
        'ship_from_name' => 'getShipFromName',
        'ship_from_attention' => 'getShipFromAttention',
        'ship_from_address' => 'getShipFromAddress',
        'ship_from_city' => 'getShipFromCity',
        'ship_from_state' => 'getShipFromState',
        'ship_from_zip' => 'getShipFromZip',
        'ship_from_country' => 'getShipFromCountry',
        'sid' => 'getSid',
        'is_ship_from_fob' => 'getIsShipFromFob',
        'ship_to_name' => 'getShipToName',
        'ship_to_attention' => 'getShipToAttention',
        'ship_to_address' => 'getShipToAddress',
        'ship_to_city' => 'getShipToCity',
        'ship_to_state' => 'getShipToState',
        'ship_to_zip' => 'getShipToZip',
        'ship_to_country' => 'getShipToCountry',
        'ship_to_location_no' => 'getShipToLocationNo',
        'cid' => 'getCid',
        'is_ship_to_fob' => 'getIsShipToFob',
        'bill_to_name' => 'getBillToName',
        'bill_to_attention' => 'getBillToAttention',
        'bill_to_address' => 'getBillToAddress',
        'bill_to_city' => 'getBillToCity',
        'bill_to_state' => 'getBillToState',
        'bill_to_zip' => 'getBillToZip',
        'bill_to_country' => 'getBillToCountry',
        'is_trailer_loaded_by_shipper' => 'getIsTrailerLoadedByShipper',
        'by_driver' => 'getByDriver',
        'cod_amount' => 'getCodAmount',
        'fee_terms_collect' => 'getFeeTermsCollect',
        'fee_terms_prepaid' => 'getFeeTermsPrepaid',
        'customer_check_acceptable' => 'getCustomerCheckAcceptable',
        'carrier_name' => 'getCarrierName',
        'trailer_no' => 'getTrailerNo',
        'seal_no' => 'getSealNo',
        'scac' => 'getScac',
        'pro_no' => 'getProNo',
        'prepaid' => 'getPrepaid',
        'collect' => 'getCollect',
        'third_party' => 'getThirdParty',
        'is_this_a_master_bol' => 'getIsThisAMasterBol',
        'master_bol_id' => 'getMasterBolId',
        'is_freight_counted_by_shipper' => 'getIsFreightCountedByShipper',
        'by_driver_pallets' => 'getByDriverPallets',
        'by_driver_pieces' => 'getByDriverPieces',
        'special_instructions' => 'getSpecialInstructions',
        'order_info_lines' => 'getOrderInfoLines',
        'carrier_info_lines' => 'getCarrierInfoLines',
        'custom_fields' => 'getCustomFields'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $id 
      * @var int
      */
    protected $id;
    
    /**
      * $create_date 
      * @var \DateTime
      */
    protected $create_date;
    
    /**
      * $modify_date 
      * @var \DateTime
      */
    protected $modify_date;
    
    /**
      * $lob_id 
      * @var int
      */
    protected $lob_id;
    
    /**
      * $order_no 
      * @var Number
      */
    protected $order_no;
    
    /**
      * $bol_no 
      * @var string
      */
    protected $bol_no;
    
    /**
      * $bol_date 
      * @var \DateTime
      */
    protected $bol_date;
    
    /**
      * $ship_from_name 
      * @var string
      */
    protected $ship_from_name;
    
    /**
      * $ship_from_attention 
      * @var string
      */
    protected $ship_from_attention;
    
    /**
      * $ship_from_address 
      * @var string
      */
    protected $ship_from_address;
    
    /**
      * $ship_from_city 
      * @var string
      */
    protected $ship_from_city;
    
    /**
      * $ship_from_state 
      * @var string
      */
    protected $ship_from_state;
    
    /**
      * $ship_from_zip 
      * @var string
      */
    protected $ship_from_zip;
    
    /**
      * $ship_from_country 
      * @var string
      */
    protected $ship_from_country;
    
    /**
      * $sid 
      * @var string
      */
    protected $sid;
    
    /**
      * $is_ship_from_fob 
      * @var bool
      */
    protected $is_ship_from_fob = false;
    
    /**
      * $ship_to_name 
      * @var string
      */
    protected $ship_to_name;
    
    /**
      * $ship_to_attention 
      * @var string
      */
    protected $ship_to_attention;
    
    /**
      * $ship_to_address 
      * @var string
      */
    protected $ship_to_address;
    
    /**
      * $ship_to_city 
      * @var string
      */
    protected $ship_to_city;
    
    /**
      * $ship_to_state 
      * @var string
      */
    protected $ship_to_state;
    
    /**
      * $ship_to_zip 
      * @var string
      */
    protected $ship_to_zip;
    
    /**
      * $ship_to_country 
      * @var string
      */
    protected $ship_to_country;
    
    /**
      * $ship_to_location_no 
      * @var string
      */
    protected $ship_to_location_no;
    
    /**
      * $cid 
      * @var string
      */
    protected $cid;
    
    /**
      * $is_ship_to_fob 
      * @var bool
      */
    protected $is_ship_to_fob = false;
    
    /**
      * $bill_to_name 
      * @var string
      */
    protected $bill_to_name;
    
    /**
      * $bill_to_attention 
      * @var string
      */
    protected $bill_to_attention;
    
    /**
      * $bill_to_address 
      * @var string
      */
    protected $bill_to_address;
    
    /**
      * $bill_to_city 
      * @var string
      */
    protected $bill_to_city;
    
    /**
      * $bill_to_state 
      * @var string
      */
    protected $bill_to_state;
    
    /**
      * $bill_to_zip 
      * @var string
      */
    protected $bill_to_zip;
    
    /**
      * $bill_to_country 
      * @var string
      */
    protected $bill_to_country;
    
    /**
      * $is_trailer_loaded_by_shipper 
      * @var bool
      */
    protected $is_trailer_loaded_by_shipper = false;
    
    /**
      * $by_driver 
      * @var bool
      */
    protected $by_driver = false;
    
    /**
      * $cod_amount 
      * @var Number
      */
    protected $cod_amount;
    
    /**
      * $fee_terms_collect 
      * @var bool
      */
    protected $fee_terms_collect = false;
    
    /**
      * $fee_terms_prepaid 
      * @var bool
      */
    protected $fee_terms_prepaid = false;
    
    /**
      * $customer_check_acceptable 
      * @var bool
      */
    protected $customer_check_acceptable = false;
    
    /**
      * $carrier_name 
      * @var string
      */
    protected $carrier_name;
    
    /**
      * $trailer_no 
      * @var string
      */
    protected $trailer_no;
    
    /**
      * $seal_no 
      * @var string
      */
    protected $seal_no;
    
    /**
      * $scac 
      * @var string
      */
    protected $scac;
    
    /**
      * $pro_no 
      * @var string
      */
    protected $pro_no;
    
    /**
      * $prepaid 
      * @var bool
      */
    protected $prepaid = false;
    
    /**
      * $collect 
      * @var bool
      */
    protected $collect = false;
    
    /**
      * $third_party 
      * @var bool
      */
    protected $third_party = false;
    
    /**
      * $is_this_a_master_bol 
      * @var bool
      */
    protected $is_this_a_master_bol = false;
    
    /**
      * $master_bol_id 
      * @var int
      */
    protected $master_bol_id;
    
    /**
      * $is_freight_counted_by_shipper 
      * @var bool
      */
    protected $is_freight_counted_by_shipper = false;
    
    /**
      * $by_driver_pallets 
      * @var bool
      */
    protected $by_driver_pallets = false;
    
    /**
      * $by_driver_pieces 
      * @var bool
      */
    protected $by_driver_pieces = false;
    
    /**
      * $special_instructions 
      * @var string
      */
    protected $special_instructions;
    
    /**
      * $order_info_lines 
      * @var \Infoplus\Model\BillOfLadingOrderInfoLine[]
      */
    protected $order_info_lines;
    
    /**
      * $carrier_info_lines 
      * @var \Infoplus\Model\BillOfLadingCarrierInfoLine[]
      */
    protected $carrier_info_lines;
    
    /**
      * $custom_fields 
      * @var map[string,object]
      */
    protected $custom_fields;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->id = $data["id"];
            $this->create_date = $data["create_date"];
            $this->modify_date = $data["modify_date"];
            $this->lob_id = $data["lob_id"];
            $this->order_no = $data["order_no"];
            $this->bol_no = $data["bol_no"];
            $this->bol_date = $data["bol_date"];
            $this->ship_from_name = $data["ship_from_name"];
            $this->ship_from_attention = $data["ship_from_attention"];
            $this->ship_from_address = $data["ship_from_address"];
            $this->ship_from_city = $data["ship_from_city"];
            $this->ship_from_state = $data["ship_from_state"];
            $this->ship_from_zip = $data["ship_from_zip"];
            $this->ship_from_country = $data["ship_from_country"];
            $this->sid = $data["sid"];
            $this->is_ship_from_fob = $data["is_ship_from_fob"];
            $this->ship_to_name = $data["ship_to_name"];
            $this->ship_to_attention = $data["ship_to_attention"];
            $this->ship_to_address = $data["ship_to_address"];
            $this->ship_to_city = $data["ship_to_city"];
            $this->ship_to_state = $data["ship_to_state"];
            $this->ship_to_zip = $data["ship_to_zip"];
            $this->ship_to_country = $data["ship_to_country"];
            $this->ship_to_location_no = $data["ship_to_location_no"];
            $this->cid = $data["cid"];
            $this->is_ship_to_fob = $data["is_ship_to_fob"];
            $this->bill_to_name = $data["bill_to_name"];
            $this->bill_to_attention = $data["bill_to_attention"];
            $this->bill_to_address = $data["bill_to_address"];
            $this->bill_to_city = $data["bill_to_city"];
            $this->bill_to_state = $data["bill_to_state"];
            $this->bill_to_zip = $data["bill_to_zip"];
            $this->bill_to_country = $data["bill_to_country"];
            $this->is_trailer_loaded_by_shipper = $data["is_trailer_loaded_by_shipper"];
            $this->by_driver = $data["by_driver"];
            $this->cod_amount = $data["cod_amount"];
            $this->fee_terms_collect = $data["fee_terms_collect"];
            $this->fee_terms_prepaid = $data["fee_terms_prepaid"];
            $this->customer_check_acceptable = $data["customer_check_acceptable"];
            $this->carrier_name = $data["carrier_name"];
            $this->trailer_no = $data["trailer_no"];
            $this->seal_no = $data["seal_no"];
            $this->scac = $data["scac"];
            $this->pro_no = $data["pro_no"];
            $this->prepaid = $data["prepaid"];
            $this->collect = $data["collect"];
            $this->third_party = $data["third_party"];
            $this->is_this_a_master_bol = $data["is_this_a_master_bol"];
            $this->master_bol_id = $data["master_bol_id"];
            $this->is_freight_counted_by_shipper = $data["is_freight_counted_by_shipper"];
            $this->by_driver_pallets = $data["by_driver_pallets"];
            $this->by_driver_pieces = $data["by_driver_pieces"];
            $this->special_instructions = $data["special_instructions"];
            $this->order_info_lines = $data["order_info_lines"];
            $this->carrier_info_lines = $data["carrier_info_lines"];
            $this->custom_fields = $data["custom_fields"];
        }
    }
    
    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
  
    /**
     * Sets id
     * @param int $id 
     * @return $this
     */
    public function setId($id)
    {
        
        $this->id = $id;
        return $this;
    }
    
    /**
     * Gets create_date
     * @return \DateTime
     */
    public function getCreateDate()
    {
        return $this->create_date;
    }
  
    /**
     * Sets create_date
     * @param \DateTime $create_date 
     * @return $this
     */
    public function setCreateDate($create_date)
    {
        
        $this->create_date = $create_date;
        return $this;
    }
    
    /**
     * Gets modify_date
     * @return \DateTime
     */
    public function getModifyDate()
    {
        return $this->modify_date;
    }
  
    /**
     * Sets modify_date
     * @param \DateTime $modify_date 
     * @return $this
     */
    public function setModifyDate($modify_date)
    {
        
        $this->modify_date = $modify_date;
        return $this;
    }
    
    /**
     * Gets lob_id
     * @return int
     */
    public function getLobId()
    {
        return $this->lob_id;
    }
  
    /**
     * Sets lob_id
     * @param int $lob_id 
     * @return $this
     */
    public function setLobId($lob_id)
    {
        
        $this->lob_id = $lob_id;
        return $this;
    }
    
    /**
     * Gets order_no
     * @return Number
     */
    public function getOrderNo()
    {
        return $this->order_no;
    }
  
    /**
     * Sets order_no
     * @param Number $order_no 
     * @return $this
     */
    public function setOrderNo($order_no)
    {
        
        $this->order_no = $order_no;
        return $this;
    }
    
    /**
     * Gets bol_no
     * @return string
     */
    public function getBolNo()
    {
        return $this->bol_no;
    }
  
    /**
     * Sets bol_no
     * @param string $bol_no 
     * @return $this
     */
    public function setBolNo($bol_no)
    {
        
        $this->bol_no = $bol_no;
        return $this;
    }
    
    /**
     * Gets bol_date
     * @return \DateTime
     */
    public function getBolDate()
    {
        return $this->bol_date;
    }
  
    /**
     * Sets bol_date
     * @param \DateTime $bol_date 
     * @return $this
     */
    public function setBolDate($bol_date)
    {
        
        $this->bol_date = $bol_date;
        return $this;
    }
    
    /**
     * Gets ship_from_name
     * @return string
     */
    public function getShipFromName()
    {
        return $this->ship_from_name;
    }
  
    /**
     * Sets ship_from_name
     * @param string $ship_from_name 
     * @return $this
     */
    public function setShipFromName($ship_from_name)
    {
        
        $this->ship_from_name = $ship_from_name;
        return $this;
    }
    
    /**
     * Gets ship_from_attention
     * @return string
     */
    public function getShipFromAttention()
    {
        return $this->ship_from_attention;
    }
  
    /**
     * Sets ship_from_attention
     * @param string $ship_from_attention 
     * @return $this
     */
    public function setShipFromAttention($ship_from_attention)
    {
        
        $this->ship_from_attention = $ship_from_attention;
        return $this;
    }
    
    /**
     * Gets ship_from_address
     * @return string
     */
    public function getShipFromAddress()
    {
        return $this->ship_from_address;
    }
  
    /**
     * Sets ship_from_address
     * @param string $ship_from_address 
     * @return $this
     */
    public function setShipFromAddress($ship_from_address)
    {
        
        $this->ship_from_address = $ship_from_address;
        return $this;
    }
    
    /**
     * Gets ship_from_city
     * @return string
     */
    public function getShipFromCity()
    {
        return $this->ship_from_city;
    }
  
    /**
     * Sets ship_from_city
     * @param string $ship_from_city 
     * @return $this
     */
    public function setShipFromCity($ship_from_city)
    {
        
        $this->ship_from_city = $ship_from_city;
        return $this;
    }
    
    /**
     * Gets ship_from_state
     * @return string
     */
    public function getShipFromState()
    {
        return $this->ship_from_state;
    }
  
    /**
     * Sets ship_from_state
     * @param string $ship_from_state 
     * @return $this
     */
    public function setShipFromState($ship_from_state)
    {
        
        $this->ship_from_state = $ship_from_state;
        return $this;
    }
    
    /**
     * Gets ship_from_zip
     * @return string
     */
    public function getShipFromZip()
    {
        return $this->ship_from_zip;
    }
  
    /**
     * Sets ship_from_zip
     * @param string $ship_from_zip 
     * @return $this
     */
    public function setShipFromZip($ship_from_zip)
    {
        
        $this->ship_from_zip = $ship_from_zip;
        return $this;
    }
    
    /**
     * Gets ship_from_country
     * @return string
     */
    public function getShipFromCountry()
    {
        return $this->ship_from_country;
    }
  
    /**
     * Sets ship_from_country
     * @param string $ship_from_country 
     * @return $this
     */
    public function setShipFromCountry($ship_from_country)
    {
        
        $this->ship_from_country = $ship_from_country;
        return $this;
    }
    
    /**
     * Gets sid
     * @return string
     */
    public function getSid()
    {
        return $this->sid;
    }
  
    /**
     * Sets sid
     * @param string $sid 
     * @return $this
     */
    public function setSid($sid)
    {
        
        $this->sid = $sid;
        return $this;
    }
    
    /**
     * Gets is_ship_from_fob
     * @return bool
     */
    public function getIsShipFromFob()
    {
        return $this->is_ship_from_fob;
    }
  
    /**
     * Sets is_ship_from_fob
     * @param bool $is_ship_from_fob 
     * @return $this
     */
    public function setIsShipFromFob($is_ship_from_fob)
    {
        
        $this->is_ship_from_fob = $is_ship_from_fob;
        return $this;
    }
    
    /**
     * Gets ship_to_name
     * @return string
     */
    public function getShipToName()
    {
        return $this->ship_to_name;
    }
  
    /**
     * Sets ship_to_name
     * @param string $ship_to_name 
     * @return $this
     */
    public function setShipToName($ship_to_name)
    {
        
        $this->ship_to_name = $ship_to_name;
        return $this;
    }
    
    /**
     * Gets ship_to_attention
     * @return string
     */
    public function getShipToAttention()
    {
        return $this->ship_to_attention;
    }
  
    /**
     * Sets ship_to_attention
     * @param string $ship_to_attention 
     * @return $this
     */
    public function setShipToAttention($ship_to_attention)
    {
        
        $this->ship_to_attention = $ship_to_attention;
        return $this;
    }
    
    /**
     * Gets ship_to_address
     * @return string
     */
    public function getShipToAddress()
    {
        return $this->ship_to_address;
    }
  
    /**
     * Sets ship_to_address
     * @param string $ship_to_address 
     * @return $this
     */
    public function setShipToAddress($ship_to_address)
    {
        
        $this->ship_to_address = $ship_to_address;
        return $this;
    }
    
    /**
     * Gets ship_to_city
     * @return string
     */
    public function getShipToCity()
    {
        return $this->ship_to_city;
    }
  
    /**
     * Sets ship_to_city
     * @param string $ship_to_city 
     * @return $this
     */
    public function setShipToCity($ship_to_city)
    {
        
        $this->ship_to_city = $ship_to_city;
        return $this;
    }
    
    /**
     * Gets ship_to_state
     * @return string
     */
    public function getShipToState()
    {
        return $this->ship_to_state;
    }
  
    /**
     * Sets ship_to_state
     * @param string $ship_to_state 
     * @return $this
     */
    public function setShipToState($ship_to_state)
    {
        
        $this->ship_to_state = $ship_to_state;
        return $this;
    }
    
    /**
     * Gets ship_to_zip
     * @return string
     */
    public function getShipToZip()
    {
        return $this->ship_to_zip;
    }
  
    /**
     * Sets ship_to_zip
     * @param string $ship_to_zip 
     * @return $this
     */
    public function setShipToZip($ship_to_zip)
    {
        
        $this->ship_to_zip = $ship_to_zip;
        return $this;
    }
    
    /**
     * Gets ship_to_country
     * @return string
     */
    public function getShipToCountry()
    {
        return $this->ship_to_country;
    }
  
    /**
     * Sets ship_to_country
     * @param string $ship_to_country 
     * @return $this
     */
    public function setShipToCountry($ship_to_country)
    {
        
        $this->ship_to_country = $ship_to_country;
        return $this;
    }
    
    /**
     * Gets ship_to_location_no
     * @return string
     */
    public function getShipToLocationNo()
    {
        return $this->ship_to_location_no;
    }
  
    /**
     * Sets ship_to_location_no
     * @param string $ship_to_location_no 
     * @return $this
     */
    public function setShipToLocationNo($ship_to_location_no)
    {
        
        $this->ship_to_location_no = $ship_to_location_no;
        return $this;
    }
    
    /**
     * Gets cid
     * @return string
     */
    public function getCid()
    {
        return $this->cid;
    }
  
    /**
     * Sets cid
     * @param string $cid 
     * @return $this
     */
    public function setCid($cid)
    {
        
        $this->cid = $cid;
        return $this;
    }
    
    /**
     * Gets is_ship_to_fob
     * @return bool
     */
    public function getIsShipToFob()
    {
        return $this->is_ship_to_fob;
    }
  
    /**
     * Sets is_ship_to_fob
     * @param bool $is_ship_to_fob 
     * @return $this
     */
    public function setIsShipToFob($is_ship_to_fob)
    {
        
        $this->is_ship_to_fob = $is_ship_to_fob;
        return $this;
    }
    
    /**
     * Gets bill_to_name
     * @return string
     */
    public function getBillToName()
    {
        return $this->bill_to_name;
    }
  
    /**
     * Sets bill_to_name
     * @param string $bill_to_name 
     * @return $this
     */
    public function setBillToName($bill_to_name)
    {
        
        $this->bill_to_name = $bill_to_name;
        return $this;
    }
    
    /**
     * Gets bill_to_attention
     * @return string
     */
    public function getBillToAttention()
    {
        return $this->bill_to_attention;
    }
  
    /**
     * Sets bill_to_attention
     * @param string $bill_to_attention 
     * @return $this
     */
    public function setBillToAttention($bill_to_attention)
    {
        
        $this->bill_to_attention = $bill_to_attention;
        return $this;
    }
    
    /**
     * Gets bill_to_address
     * @return string
     */
    public function getBillToAddress()
    {
        return $this->bill_to_address;
    }
  
    /**
     * Sets bill_to_address
     * @param string $bill_to_address 
     * @return $this
     */
    public function setBillToAddress($bill_to_address)
    {
        
        $this->bill_to_address = $bill_to_address;
        return $this;
    }
    
    /**
     * Gets bill_to_city
     * @return string
     */
    public function getBillToCity()
    {
        return $this->bill_to_city;
    }
  
    /**
     * Sets bill_to_city
     * @param string $bill_to_city 
     * @return $this
     */
    public function setBillToCity($bill_to_city)
    {
        
        $this->bill_to_city = $bill_to_city;
        return $this;
    }
    
    /**
     * Gets bill_to_state
     * @return string
     */
    public function getBillToState()
    {
        return $this->bill_to_state;
    }
  
    /**
     * Sets bill_to_state
     * @param string $bill_to_state 
     * @return $this
     */
    public function setBillToState($bill_to_state)
    {
        
        $this->bill_to_state = $bill_to_state;
        return $this;
    }
    
    /**
     * Gets bill_to_zip
     * @return string
     */
    public function getBillToZip()
    {
        return $this->bill_to_zip;
    }
  
    /**
     * Sets bill_to_zip
     * @param string $bill_to_zip 
     * @return $this
     */
    public function setBillToZip($bill_to_zip)
    {
        
        $this->bill_to_zip = $bill_to_zip;
        return $this;
    }
    
    /**
     * Gets bill_to_country
     * @return string
     */
    public function getBillToCountry()
    {
        return $this->bill_to_country;
    }
  
    /**
     * Sets bill_to_country
     * @param string $bill_to_country 
     * @return $this
     */
    public function setBillToCountry($bill_to_country)
    {
        
        $this->bill_to_country = $bill_to_country;
        return $this;
    }
    
    /**
     * Gets is_trailer_loaded_by_shipper
     * @return bool
     */
    public function getIsTrailerLoadedByShipper()
    {
        return $this->is_trailer_loaded_by_shipper;
    }
  
    /**
     * Sets is_trailer_loaded_by_shipper
     * @param bool $is_trailer_loaded_by_shipper 
     * @return $this
     */
    public function setIsTrailerLoadedByShipper($is_trailer_loaded_by_shipper)
    {
        
        $this->is_trailer_loaded_by_shipper = $is_trailer_loaded_by_shipper;
        return $this;
    }
    
    /**
     * Gets by_driver
     * @return bool
     */
    public function getByDriver()
    {
        return $this->by_driver;
    }
  
    /**
     * Sets by_driver
     * @param bool $by_driver 
     * @return $this
     */
    public function setByDriver($by_driver)
    {
        
        $this->by_driver = $by_driver;
        return $this;
    }
    
    /**
     * Gets cod_amount
     * @return Number
     */
    public function getCodAmount()
    {
        return $this->cod_amount;
    }
  
    /**
     * Sets cod_amount
     * @param Number $cod_amount 
     * @return $this
     */
    public function setCodAmount($cod_amount)
    {
        
        $this->cod_amount = $cod_amount;
        return $this;
    }
    
    /**
     * Gets fee_terms_collect
     * @return bool
     */
    public function getFeeTermsCollect()
    {
        return $this->fee_terms_collect;
    }
  
    /**
     * Sets fee_terms_collect
     * @param bool $fee_terms_collect 
     * @return $this
     */
    public function setFeeTermsCollect($fee_terms_collect)
    {
        
        $this->fee_terms_collect = $fee_terms_collect;
        return $this;
    }
    
    /**
     * Gets fee_terms_prepaid
     * @return bool
     */
    public function getFeeTermsPrepaid()
    {
        return $this->fee_terms_prepaid;
    }
  
    /**
     * Sets fee_terms_prepaid
     * @param bool $fee_terms_prepaid 
     * @return $this
     */
    public function setFeeTermsPrepaid($fee_terms_prepaid)
    {
        
        $this->fee_terms_prepaid = $fee_terms_prepaid;
        return $this;
    }
    
    /**
     * Gets customer_check_acceptable
     * @return bool
     */
    public function getCustomerCheckAcceptable()
    {
        return $this->customer_check_acceptable;
    }
  
    /**
     * Sets customer_check_acceptable
     * @param bool $customer_check_acceptable 
     * @return $this
     */
    public function setCustomerCheckAcceptable($customer_check_acceptable)
    {
        
        $this->customer_check_acceptable = $customer_check_acceptable;
        return $this;
    }
    
    /**
     * Gets carrier_name
     * @return string
     */
    public function getCarrierName()
    {
        return $this->carrier_name;
    }
  
    /**
     * Sets carrier_name
     * @param string $carrier_name 
     * @return $this
     */
    public function setCarrierName($carrier_name)
    {
        
        $this->carrier_name = $carrier_name;
        return $this;
    }
    
    /**
     * Gets trailer_no
     * @return string
     */
    public function getTrailerNo()
    {
        return $this->trailer_no;
    }
  
    /**
     * Sets trailer_no
     * @param string $trailer_no 
     * @return $this
     */
    public function setTrailerNo($trailer_no)
    {
        
        $this->trailer_no = $trailer_no;
        return $this;
    }
    
    /**
     * Gets seal_no
     * @return string
     */
    public function getSealNo()
    {
        return $this->seal_no;
    }
  
    /**
     * Sets seal_no
     * @param string $seal_no 
     * @return $this
     */
    public function setSealNo($seal_no)
    {
        
        $this->seal_no = $seal_no;
        return $this;
    }
    
    /**
     * Gets scac
     * @return string
     */
    public function getScac()
    {
        return $this->scac;
    }
  
    /**
     * Sets scac
     * @param string $scac 
     * @return $this
     */
    public function setScac($scac)
    {
        
        $this->scac = $scac;
        return $this;
    }
    
    /**
     * Gets pro_no
     * @return string
     */
    public function getProNo()
    {
        return $this->pro_no;
    }
  
    /**
     * Sets pro_no
     * @param string $pro_no 
     * @return $this
     */
    public function setProNo($pro_no)
    {
        
        $this->pro_no = $pro_no;
        return $this;
    }
    
    /**
     * Gets prepaid
     * @return bool
     */
    public function getPrepaid()
    {
        return $this->prepaid;
    }
  
    /**
     * Sets prepaid
     * @param bool $prepaid 
     * @return $this
     */
    public function setPrepaid($prepaid)
    {
        
        $this->prepaid = $prepaid;
        return $this;
    }
    
    /**
     * Gets collect
     * @return bool
     */
    public function getCollect()
    {
        return $this->collect;
    }
  
    /**
     * Sets collect
     * @param bool $collect 
     * @return $this
     */
    public function setCollect($collect)
    {
        
        $this->collect = $collect;
        return $this;
    }
    
    /**
     * Gets third_party
     * @return bool
     */
    public function getThirdParty()
    {
        return $this->third_party;
    }
  
    /**
     * Sets third_party
     * @param bool $third_party 
     * @return $this
     */
    public function setThirdParty($third_party)
    {
        
        $this->third_party = $third_party;
        return $this;
    }
    
    /**
     * Gets is_this_a_master_bol
     * @return bool
     */
    public function getIsThisAMasterBol()
    {
        return $this->is_this_a_master_bol;
    }
  
    /**
     * Sets is_this_a_master_bol
     * @param bool $is_this_a_master_bol 
     * @return $this
     */
    public function setIsThisAMasterBol($is_this_a_master_bol)
    {
        
        $this->is_this_a_master_bol = $is_this_a_master_bol;
        return $this;
    }
    
    /**
     * Gets master_bol_id
     * @return int
     */
    public function getMasterBolId()
    {
        return $this->master_bol_id;
    }
  
    /**
     * Sets master_bol_id
     * @param int $master_bol_id 
     * @return $this
     */
    public function setMasterBolId($master_bol_id)
    {
        
        $this->master_bol_id = $master_bol_id;
        return $this;
    }
    
    /**
     * Gets is_freight_counted_by_shipper
     * @return bool
     */
    public function getIsFreightCountedByShipper()
    {
        return $this->is_freight_counted_by_shipper;
    }
  
    /**
     * Sets is_freight_counted_by_shipper
     * @param bool $is_freight_counted_by_shipper 
     * @return $this
     */
    public function setIsFreightCountedByShipper($is_freight_counted_by_shipper)
    {
        
        $this->is_freight_counted_by_shipper = $is_freight_counted_by_shipper;
        return $this;
    }
    
    /**
     * Gets by_driver_pallets
     * @return bool
     */
    public function getByDriverPallets()
    {
        return $this->by_driver_pallets;
    }
  
    /**
     * Sets by_driver_pallets
     * @param bool $by_driver_pallets 
     * @return $this
     */
    public function setByDriverPallets($by_driver_pallets)
    {
        
        $this->by_driver_pallets = $by_driver_pallets;
        return $this;
    }
    
    /**
     * Gets by_driver_pieces
     * @return bool
     */
    public function getByDriverPieces()
    {
        return $this->by_driver_pieces;
    }
  
    /**
     * Sets by_driver_pieces
     * @param bool $by_driver_pieces 
     * @return $this
     */
    public function setByDriverPieces($by_driver_pieces)
    {
        
        $this->by_driver_pieces = $by_driver_pieces;
        return $this;
    }
    
    /**
     * Gets special_instructions
     * @return string
     */
    public function getSpecialInstructions()
    {
        return $this->special_instructions;
    }
  
    /**
     * Sets special_instructions
     * @param string $special_instructions 
     * @return $this
     */
    public function setSpecialInstructions($special_instructions)
    {
        
        $this->special_instructions = $special_instructions;
        return $this;
    }
    
    /**
     * Gets order_info_lines
     * @return \Infoplus\Model\BillOfLadingOrderInfoLine[]
     */
    public function getOrderInfoLines()
    {
        return $this->order_info_lines;
    }
  
    /**
     * Sets order_info_lines
     * @param \Infoplus\Model\BillOfLadingOrderInfoLine[] $order_info_lines 
     * @return $this
     */
    public function setOrderInfoLines($order_info_lines)
    {
        
        $this->order_info_lines = $order_info_lines;
        return $this;
    }
    
    /**
     * Gets carrier_info_lines
     * @return \Infoplus\Model\BillOfLadingCarrierInfoLine[]
     */
    public function getCarrierInfoLines()
    {
        return $this->carrier_info_lines;
    }
  
    /**
     * Sets carrier_info_lines
     * @param \Infoplus\Model\BillOfLadingCarrierInfoLine[] $carrier_info_lines 
     * @return $this
     */
    public function setCarrierInfoLines($carrier_info_lines)
    {
        
        $this->carrier_info_lines = $carrier_info_lines;
        return $this;
    }
    
    /**
     * Gets custom_fields
     * @return map[string,object]
     */
    public function getCustomFields()
    {
        return $this->custom_fields;
    }
  
    /**
     * Sets custom_fields
     * @param map[string,object] $custom_fields 
     * @return $this
     */
    public function setCustomFields($custom_fields)
    {
        
        $this->custom_fields = $custom_fields;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Infoplus\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Infoplus\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
