<?php
/**
 * Customer
 *
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Infoplus\Model;

use \ArrayAccess;
/**
 * Customer Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Infoplus
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Customer implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'id' => 'int',
        'lob_id' => 'int',
        'customer_no' => 'string',
        'name' => 'string',
        'attention' => 'string',
        'street' => 'string',
        'street2' => 'string',
        'street3_province' => 'string',
        'city' => 'string',
        'state' => 'string',
        'zip_code' => 'string',
        'country' => 'string',
        'phone' => 'string',
        'fax' => 'string',
        'email' => 'string',
        'boss_branch' => 'string',
        'package_carrier_id' => 'int',
        'truck_carrier_id' => 'int',
        'weight_break' => 'int',
        'sector' => 'string',
        'division' => 'int',
        'cost_center' => 'string',
        'county' => 'string',
        'area' => 'string',
        'customer_type' => 'string',
        'mass_level' => 'string',
        'mass_factor' => 'double',
        'price_level' => 'string',
        'open_date' => '\DateTime',
        'close_date' => '\DateTime',
        'restriction_percent' => 'int',
        'external_id' => 'string',
        'cycle_date' => '\DateTime',
        'manager' => 'string',
        'alternate_inventory' => 'int',
        'pin' => 'string',
        'fax_gone' => 'string',
        'residential' => 'string',
        'csr_branch' => 'string',
        'extrinsic_text1' => 'string',
        'extrinsic_text2' => 'string',
        'extrinsic_text3' => 'string',
        'extrinsic_number1' => 'int',
        'extrinsic_number2' => 'int',
        'extrinsic_decimal1' => 'double',
        'extrinsic_decimal2' => 'double',
        'modify_date' => '\DateTime',
        'oms_customer_id' => 'int'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'id' => 'id',
        'lob_id' => 'lobId',
        'customer_no' => 'customerNo',
        'name' => 'name',
        'attention' => 'attention',
        'street' => 'street',
        'street2' => 'street2',
        'street3_province' => 'street3Province',
        'city' => 'city',
        'state' => 'state',
        'zip_code' => 'zipCode',
        'country' => 'country',
        'phone' => 'phone',
        'fax' => 'fax',
        'email' => 'email',
        'boss_branch' => 'bossBranch',
        'package_carrier_id' => 'packageCarrierId',
        'truck_carrier_id' => 'truckCarrierId',
        'weight_break' => 'weightBreak',
        'sector' => 'sector',
        'division' => 'division',
        'cost_center' => 'costCenter',
        'county' => 'county',
        'area' => 'area',
        'customer_type' => 'customerType',
        'mass_level' => 'massLevel',
        'mass_factor' => 'massFactor',
        'price_level' => 'priceLevel',
        'open_date' => 'openDate',
        'close_date' => 'closeDate',
        'restriction_percent' => 'restrictionPercent',
        'external_id' => 'externalId',
        'cycle_date' => 'cycleDate',
        'manager' => 'manager',
        'alternate_inventory' => 'alternateInventory',
        'pin' => 'pin',
        'fax_gone' => 'faxGone',
        'residential' => 'residential',
        'csr_branch' => 'csrBranch',
        'extrinsic_text1' => 'extrinsicText1',
        'extrinsic_text2' => 'extrinsicText2',
        'extrinsic_text3' => 'extrinsicText3',
        'extrinsic_number1' => 'extrinsicNumber1',
        'extrinsic_number2' => 'extrinsicNumber2',
        'extrinsic_decimal1' => 'extrinsicDecimal1',
        'extrinsic_decimal2' => 'extrinsicDecimal2',
        'modify_date' => 'modifyDate',
        'oms_customer_id' => 'omsCustomerId'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'id' => 'setId',
        'lob_id' => 'setLobId',
        'customer_no' => 'setCustomerNo',
        'name' => 'setName',
        'attention' => 'setAttention',
        'street' => 'setStreet',
        'street2' => 'setStreet2',
        'street3_province' => 'setStreet3Province',
        'city' => 'setCity',
        'state' => 'setState',
        'zip_code' => 'setZipCode',
        'country' => 'setCountry',
        'phone' => 'setPhone',
        'fax' => 'setFax',
        'email' => 'setEmail',
        'boss_branch' => 'setBossBranch',
        'package_carrier_id' => 'setPackageCarrierId',
        'truck_carrier_id' => 'setTruckCarrierId',
        'weight_break' => 'setWeightBreak',
        'sector' => 'setSector',
        'division' => 'setDivision',
        'cost_center' => 'setCostCenter',
        'county' => 'setCounty',
        'area' => 'setArea',
        'customer_type' => 'setCustomerType',
        'mass_level' => 'setMassLevel',
        'mass_factor' => 'setMassFactor',
        'price_level' => 'setPriceLevel',
        'open_date' => 'setOpenDate',
        'close_date' => 'setCloseDate',
        'restriction_percent' => 'setRestrictionPercent',
        'external_id' => 'setExternalId',
        'cycle_date' => 'setCycleDate',
        'manager' => 'setManager',
        'alternate_inventory' => 'setAlternateInventory',
        'pin' => 'setPin',
        'fax_gone' => 'setFaxGone',
        'residential' => 'setResidential',
        'csr_branch' => 'setCsrBranch',
        'extrinsic_text1' => 'setExtrinsicText1',
        'extrinsic_text2' => 'setExtrinsicText2',
        'extrinsic_text3' => 'setExtrinsicText3',
        'extrinsic_number1' => 'setExtrinsicNumber1',
        'extrinsic_number2' => 'setExtrinsicNumber2',
        'extrinsic_decimal1' => 'setExtrinsicDecimal1',
        'extrinsic_decimal2' => 'setExtrinsicDecimal2',
        'modify_date' => 'setModifyDate',
        'oms_customer_id' => 'setOmsCustomerId'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'id' => 'getId',
        'lob_id' => 'getLobId',
        'customer_no' => 'getCustomerNo',
        'name' => 'getName',
        'attention' => 'getAttention',
        'street' => 'getStreet',
        'street2' => 'getStreet2',
        'street3_province' => 'getStreet3Province',
        'city' => 'getCity',
        'state' => 'getState',
        'zip_code' => 'getZipCode',
        'country' => 'getCountry',
        'phone' => 'getPhone',
        'fax' => 'getFax',
        'email' => 'getEmail',
        'boss_branch' => 'getBossBranch',
        'package_carrier_id' => 'getPackageCarrierId',
        'truck_carrier_id' => 'getTruckCarrierId',
        'weight_break' => 'getWeightBreak',
        'sector' => 'getSector',
        'division' => 'getDivision',
        'cost_center' => 'getCostCenter',
        'county' => 'getCounty',
        'area' => 'getArea',
        'customer_type' => 'getCustomerType',
        'mass_level' => 'getMassLevel',
        'mass_factor' => 'getMassFactor',
        'price_level' => 'getPriceLevel',
        'open_date' => 'getOpenDate',
        'close_date' => 'getCloseDate',
        'restriction_percent' => 'getRestrictionPercent',
        'external_id' => 'getExternalId',
        'cycle_date' => 'getCycleDate',
        'manager' => 'getManager',
        'alternate_inventory' => 'getAlternateInventory',
        'pin' => 'getPin',
        'fax_gone' => 'getFaxGone',
        'residential' => 'getResidential',
        'csr_branch' => 'getCsrBranch',
        'extrinsic_text1' => 'getExtrinsicText1',
        'extrinsic_text2' => 'getExtrinsicText2',
        'extrinsic_text3' => 'getExtrinsicText3',
        'extrinsic_number1' => 'getExtrinsicNumber1',
        'extrinsic_number2' => 'getExtrinsicNumber2',
        'extrinsic_decimal1' => 'getExtrinsicDecimal1',
        'extrinsic_decimal2' => 'getExtrinsicDecimal2',
        'modify_date' => 'getModifyDate',
        'oms_customer_id' => 'getOmsCustomerId'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $id 
      * @var int
      */
    protected $id;
    
    /**
      * $lob_id 
      * @var int
      */
    protected $lob_id;
    
    /**
      * $customer_no 
      * @var string
      */
    protected $customer_no;
    
    /**
      * $name 
      * @var string
      */
    protected $name;
    
    /**
      * $attention 
      * @var string
      */
    protected $attention;
    
    /**
      * $street 
      * @var string
      */
    protected $street;
    
    /**
      * $street2 
      * @var string
      */
    protected $street2;
    
    /**
      * $street3_province 
      * @var string
      */
    protected $street3_province;
    
    /**
      * $city 
      * @var string
      */
    protected $city;
    
    /**
      * $state 
      * @var string
      */
    protected $state;
    
    /**
      * $zip_code 
      * @var string
      */
    protected $zip_code;
    
    /**
      * $country 
      * @var string
      */
    protected $country;
    
    /**
      * $phone 
      * @var string
      */
    protected $phone;
    
    /**
      * $fax 
      * @var string
      */
    protected $fax;
    
    /**
      * $email 
      * @var string
      */
    protected $email;
    
    /**
      * $boss_branch 
      * @var string
      */
    protected $boss_branch;
    
    /**
      * $package_carrier_id 
      * @var int
      */
    protected $package_carrier_id;
    
    /**
      * $truck_carrier_id 
      * @var int
      */
    protected $truck_carrier_id;
    
    /**
      * $weight_break 
      * @var int
      */
    protected $weight_break;
    
    /**
      * $sector 
      * @var string
      */
    protected $sector;
    
    /**
      * $division 
      * @var int
      */
    protected $division;
    
    /**
      * $cost_center 
      * @var string
      */
    protected $cost_center;
    
    /**
      * $county 
      * @var string
      */
    protected $county;
    
    /**
      * $area 
      * @var string
      */
    protected $area;
    
    /**
      * $customer_type 
      * @var string
      */
    protected $customer_type;
    
    /**
      * $mass_level 
      * @var string
      */
    protected $mass_level;
    
    /**
      * $mass_factor 
      * @var double
      */
    protected $mass_factor;
    
    /**
      * $price_level 
      * @var string
      */
    protected $price_level;
    
    /**
      * $open_date 
      * @var \DateTime
      */
    protected $open_date;
    
    /**
      * $close_date 
      * @var \DateTime
      */
    protected $close_date;
    
    /**
      * $restriction_percent 
      * @var int
      */
    protected $restriction_percent;
    
    /**
      * $external_id 
      * @var string
      */
    protected $external_id;
    
    /**
      * $cycle_date 
      * @var \DateTime
      */
    protected $cycle_date;
    
    /**
      * $manager 
      * @var string
      */
    protected $manager;
    
    /**
      * $alternate_inventory 
      * @var int
      */
    protected $alternate_inventory;
    
    /**
      * $pin 
      * @var string
      */
    protected $pin;
    
    /**
      * $fax_gone 
      * @var string
      */
    protected $fax_gone;
    
    /**
      * $residential 
      * @var string
      */
    protected $residential;
    
    /**
      * $csr_branch 
      * @var string
      */
    protected $csr_branch;
    
    /**
      * $extrinsic_text1 
      * @var string
      */
    protected $extrinsic_text1;
    
    /**
      * $extrinsic_text2 
      * @var string
      */
    protected $extrinsic_text2;
    
    /**
      * $extrinsic_text3 
      * @var string
      */
    protected $extrinsic_text3;
    
    /**
      * $extrinsic_number1 
      * @var int
      */
    protected $extrinsic_number1;
    
    /**
      * $extrinsic_number2 
      * @var int
      */
    protected $extrinsic_number2;
    
    /**
      * $extrinsic_decimal1 
      * @var double
      */
    protected $extrinsic_decimal1;
    
    /**
      * $extrinsic_decimal2 
      * @var double
      */
    protected $extrinsic_decimal2;
    
    /**
      * $modify_date 
      * @var \DateTime
      */
    protected $modify_date;
    
    /**
      * $oms_customer_id 
      * @var int
      */
    protected $oms_customer_id;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->id = $data["id"];
            $this->lob_id = $data["lob_id"];
            $this->customer_no = $data["customer_no"];
            $this->name = $data["name"];
            $this->attention = $data["attention"];
            $this->street = $data["street"];
            $this->street2 = $data["street2"];
            $this->street3_province = $data["street3_province"];
            $this->city = $data["city"];
            $this->state = $data["state"];
            $this->zip_code = $data["zip_code"];
            $this->country = $data["country"];
            $this->phone = $data["phone"];
            $this->fax = $data["fax"];
            $this->email = $data["email"];
            $this->boss_branch = $data["boss_branch"];
            $this->package_carrier_id = $data["package_carrier_id"];
            $this->truck_carrier_id = $data["truck_carrier_id"];
            $this->weight_break = $data["weight_break"];
            $this->sector = $data["sector"];
            $this->division = $data["division"];
            $this->cost_center = $data["cost_center"];
            $this->county = $data["county"];
            $this->area = $data["area"];
            $this->customer_type = $data["customer_type"];
            $this->mass_level = $data["mass_level"];
            $this->mass_factor = $data["mass_factor"];
            $this->price_level = $data["price_level"];
            $this->open_date = $data["open_date"];
            $this->close_date = $data["close_date"];
            $this->restriction_percent = $data["restriction_percent"];
            $this->external_id = $data["external_id"];
            $this->cycle_date = $data["cycle_date"];
            $this->manager = $data["manager"];
            $this->alternate_inventory = $data["alternate_inventory"];
            $this->pin = $data["pin"];
            $this->fax_gone = $data["fax_gone"];
            $this->residential = $data["residential"];
            $this->csr_branch = $data["csr_branch"];
            $this->extrinsic_text1 = $data["extrinsic_text1"];
            $this->extrinsic_text2 = $data["extrinsic_text2"];
            $this->extrinsic_text3 = $data["extrinsic_text3"];
            $this->extrinsic_number1 = $data["extrinsic_number1"];
            $this->extrinsic_number2 = $data["extrinsic_number2"];
            $this->extrinsic_decimal1 = $data["extrinsic_decimal1"];
            $this->extrinsic_decimal2 = $data["extrinsic_decimal2"];
            $this->modify_date = $data["modify_date"];
            $this->oms_customer_id = $data["oms_customer_id"];
        }
    }
    
    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
  
    /**
     * Sets id
     * @param int $id 
     * @return $this
     */
    public function setId($id)
    {
        
        $this->id = $id;
        return $this;
    }
    
    /**
     * Gets lob_id
     * @return int
     */
    public function getLobId()
    {
        return $this->lob_id;
    }
  
    /**
     * Sets lob_id
     * @param int $lob_id 
     * @return $this
     */
    public function setLobId($lob_id)
    {
        
        $this->lob_id = $lob_id;
        return $this;
    }
    
    /**
     * Gets customer_no
     * @return string
     */
    public function getCustomerNo()
    {
        return $this->customer_no;
    }
  
    /**
     * Sets customer_no
     * @param string $customer_no 
     * @return $this
     */
    public function setCustomerNo($customer_no)
    {
        
        $this->customer_no = $customer_no;
        return $this;
    }
    
    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
  
    /**
     * Sets name
     * @param string $name 
     * @return $this
     */
    public function setName($name)
    {
        
        $this->name = $name;
        return $this;
    }
    
    /**
     * Gets attention
     * @return string
     */
    public function getAttention()
    {
        return $this->attention;
    }
  
    /**
     * Sets attention
     * @param string $attention 
     * @return $this
     */
    public function setAttention($attention)
    {
        
        $this->attention = $attention;
        return $this;
    }
    
    /**
     * Gets street
     * @return string
     */
    public function getStreet()
    {
        return $this->street;
    }
  
    /**
     * Sets street
     * @param string $street 
     * @return $this
     */
    public function setStreet($street)
    {
        
        $this->street = $street;
        return $this;
    }
    
    /**
     * Gets street2
     * @return string
     */
    public function getStreet2()
    {
        return $this->street2;
    }
  
    /**
     * Sets street2
     * @param string $street2 
     * @return $this
     */
    public function setStreet2($street2)
    {
        
        $this->street2 = $street2;
        return $this;
    }
    
    /**
     * Gets street3_province
     * @return string
     */
    public function getStreet3Province()
    {
        return $this->street3_province;
    }
  
    /**
     * Sets street3_province
     * @param string $street3_province 
     * @return $this
     */
    public function setStreet3Province($street3_province)
    {
        
        $this->street3_province = $street3_province;
        return $this;
    }
    
    /**
     * Gets city
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }
  
    /**
     * Sets city
     * @param string $city 
     * @return $this
     */
    public function setCity($city)
    {
        
        $this->city = $city;
        return $this;
    }
    
    /**
     * Gets state
     * @return string
     */
    public function getState()
    {
        return $this->state;
    }
  
    /**
     * Sets state
     * @param string $state 
     * @return $this
     */
    public function setState($state)
    {
        
        $this->state = $state;
        return $this;
    }
    
    /**
     * Gets zip_code
     * @return string
     */
    public function getZipCode()
    {
        return $this->zip_code;
    }
  
    /**
     * Sets zip_code
     * @param string $zip_code 
     * @return $this
     */
    public function setZipCode($zip_code)
    {
        
        $this->zip_code = $zip_code;
        return $this;
    }
    
    /**
     * Gets country
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }
  
    /**
     * Sets country
     * @param string $country 
     * @return $this
     */
    public function setCountry($country)
    {
        
        $this->country = $country;
        return $this;
    }
    
    /**
     * Gets phone
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }
  
    /**
     * Sets phone
     * @param string $phone 
     * @return $this
     */
    public function setPhone($phone)
    {
        
        $this->phone = $phone;
        return $this;
    }
    
    /**
     * Gets fax
     * @return string
     */
    public function getFax()
    {
        return $this->fax;
    }
  
    /**
     * Sets fax
     * @param string $fax 
     * @return $this
     */
    public function setFax($fax)
    {
        
        $this->fax = $fax;
        return $this;
    }
    
    /**
     * Gets email
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }
  
    /**
     * Sets email
     * @param string $email 
     * @return $this
     */
    public function setEmail($email)
    {
        
        $this->email = $email;
        return $this;
    }
    
    /**
     * Gets boss_branch
     * @return string
     */
    public function getBossBranch()
    {
        return $this->boss_branch;
    }
  
    /**
     * Sets boss_branch
     * @param string $boss_branch 
     * @return $this
     */
    public function setBossBranch($boss_branch)
    {
        
        $this->boss_branch = $boss_branch;
        return $this;
    }
    
    /**
     * Gets package_carrier_id
     * @return int
     */
    public function getPackageCarrierId()
    {
        return $this->package_carrier_id;
    }
  
    /**
     * Sets package_carrier_id
     * @param int $package_carrier_id 
     * @return $this
     */
    public function setPackageCarrierId($package_carrier_id)
    {
        
        $this->package_carrier_id = $package_carrier_id;
        return $this;
    }
    
    /**
     * Gets truck_carrier_id
     * @return int
     */
    public function getTruckCarrierId()
    {
        return $this->truck_carrier_id;
    }
  
    /**
     * Sets truck_carrier_id
     * @param int $truck_carrier_id 
     * @return $this
     */
    public function setTruckCarrierId($truck_carrier_id)
    {
        
        $this->truck_carrier_id = $truck_carrier_id;
        return $this;
    }
    
    /**
     * Gets weight_break
     * @return int
     */
    public function getWeightBreak()
    {
        return $this->weight_break;
    }
  
    /**
     * Sets weight_break
     * @param int $weight_break 
     * @return $this
     */
    public function setWeightBreak($weight_break)
    {
        
        $this->weight_break = $weight_break;
        return $this;
    }
    
    /**
     * Gets sector
     * @return string
     */
    public function getSector()
    {
        return $this->sector;
    }
  
    /**
     * Sets sector
     * @param string $sector 
     * @return $this
     */
    public function setSector($sector)
    {
        
        $this->sector = $sector;
        return $this;
    }
    
    /**
     * Gets division
     * @return int
     */
    public function getDivision()
    {
        return $this->division;
    }
  
    /**
     * Sets division
     * @param int $division 
     * @return $this
     */
    public function setDivision($division)
    {
        
        $this->division = $division;
        return $this;
    }
    
    /**
     * Gets cost_center
     * @return string
     */
    public function getCostCenter()
    {
        return $this->cost_center;
    }
  
    /**
     * Sets cost_center
     * @param string $cost_center 
     * @return $this
     */
    public function setCostCenter($cost_center)
    {
        
        $this->cost_center = $cost_center;
        return $this;
    }
    
    /**
     * Gets county
     * @return string
     */
    public function getCounty()
    {
        return $this->county;
    }
  
    /**
     * Sets county
     * @param string $county 
     * @return $this
     */
    public function setCounty($county)
    {
        
        $this->county = $county;
        return $this;
    }
    
    /**
     * Gets area
     * @return string
     */
    public function getArea()
    {
        return $this->area;
    }
  
    /**
     * Sets area
     * @param string $area 
     * @return $this
     */
    public function setArea($area)
    {
        
        $this->area = $area;
        return $this;
    }
    
    /**
     * Gets customer_type
     * @return string
     */
    public function getCustomerType()
    {
        return $this->customer_type;
    }
  
    /**
     * Sets customer_type
     * @param string $customer_type 
     * @return $this
     */
    public function setCustomerType($customer_type)
    {
        
        $this->customer_type = $customer_type;
        return $this;
    }
    
    /**
     * Gets mass_level
     * @return string
     */
    public function getMassLevel()
    {
        return $this->mass_level;
    }
  
    /**
     * Sets mass_level
     * @param string $mass_level 
     * @return $this
     */
    public function setMassLevel($mass_level)
    {
        
        $this->mass_level = $mass_level;
        return $this;
    }
    
    /**
     * Gets mass_factor
     * @return double
     */
    public function getMassFactor()
    {
        return $this->mass_factor;
    }
  
    /**
     * Sets mass_factor
     * @param double $mass_factor 
     * @return $this
     */
    public function setMassFactor($mass_factor)
    {
        
        $this->mass_factor = $mass_factor;
        return $this;
    }
    
    /**
     * Gets price_level
     * @return string
     */
    public function getPriceLevel()
    {
        return $this->price_level;
    }
  
    /**
     * Sets price_level
     * @param string $price_level 
     * @return $this
     */
    public function setPriceLevel($price_level)
    {
        
        $this->price_level = $price_level;
        return $this;
    }
    
    /**
     * Gets open_date
     * @return \DateTime
     */
    public function getOpenDate()
    {
        return $this->open_date;
    }
  
    /**
     * Sets open_date
     * @param \DateTime $open_date 
     * @return $this
     */
    public function setOpenDate($open_date)
    {
        
        $this->open_date = $open_date;
        return $this;
    }
    
    /**
     * Gets close_date
     * @return \DateTime
     */
    public function getCloseDate()
    {
        return $this->close_date;
    }
  
    /**
     * Sets close_date
     * @param \DateTime $close_date 
     * @return $this
     */
    public function setCloseDate($close_date)
    {
        
        $this->close_date = $close_date;
        return $this;
    }
    
    /**
     * Gets restriction_percent
     * @return int
     */
    public function getRestrictionPercent()
    {
        return $this->restriction_percent;
    }
  
    /**
     * Sets restriction_percent
     * @param int $restriction_percent 
     * @return $this
     */
    public function setRestrictionPercent($restriction_percent)
    {
        
        $this->restriction_percent = $restriction_percent;
        return $this;
    }
    
    /**
     * Gets external_id
     * @return string
     */
    public function getExternalId()
    {
        return $this->external_id;
    }
  
    /**
     * Sets external_id
     * @param string $external_id 
     * @return $this
     */
    public function setExternalId($external_id)
    {
        
        $this->external_id = $external_id;
        return $this;
    }
    
    /**
     * Gets cycle_date
     * @return \DateTime
     */
    public function getCycleDate()
    {
        return $this->cycle_date;
    }
  
    /**
     * Sets cycle_date
     * @param \DateTime $cycle_date 
     * @return $this
     */
    public function setCycleDate($cycle_date)
    {
        
        $this->cycle_date = $cycle_date;
        return $this;
    }
    
    /**
     * Gets manager
     * @return string
     */
    public function getManager()
    {
        return $this->manager;
    }
  
    /**
     * Sets manager
     * @param string $manager 
     * @return $this
     */
    public function setManager($manager)
    {
        
        $this->manager = $manager;
        return $this;
    }
    
    /**
     * Gets alternate_inventory
     * @return int
     */
    public function getAlternateInventory()
    {
        return $this->alternate_inventory;
    }
  
    /**
     * Sets alternate_inventory
     * @param int $alternate_inventory 
     * @return $this
     */
    public function setAlternateInventory($alternate_inventory)
    {
        
        $this->alternate_inventory = $alternate_inventory;
        return $this;
    }
    
    /**
     * Gets pin
     * @return string
     */
    public function getPin()
    {
        return $this->pin;
    }
  
    /**
     * Sets pin
     * @param string $pin 
     * @return $this
     */
    public function setPin($pin)
    {
        
        $this->pin = $pin;
        return $this;
    }
    
    /**
     * Gets fax_gone
     * @return string
     */
    public function getFaxGone()
    {
        return $this->fax_gone;
    }
  
    /**
     * Sets fax_gone
     * @param string $fax_gone 
     * @return $this
     */
    public function setFaxGone($fax_gone)
    {
        
        $this->fax_gone = $fax_gone;
        return $this;
    }
    
    /**
     * Gets residential
     * @return string
     */
    public function getResidential()
    {
        return $this->residential;
    }
  
    /**
     * Sets residential
     * @param string $residential 
     * @return $this
     */
    public function setResidential($residential)
    {
        
        $this->residential = $residential;
        return $this;
    }
    
    /**
     * Gets csr_branch
     * @return string
     */
    public function getCsrBranch()
    {
        return $this->csr_branch;
    }
  
    /**
     * Sets csr_branch
     * @param string $csr_branch 
     * @return $this
     */
    public function setCsrBranch($csr_branch)
    {
        
        $this->csr_branch = $csr_branch;
        return $this;
    }
    
    /**
     * Gets extrinsic_text1
     * @return string
     */
    public function getExtrinsicText1()
    {
        return $this->extrinsic_text1;
    }
  
    /**
     * Sets extrinsic_text1
     * @param string $extrinsic_text1 
     * @return $this
     */
    public function setExtrinsicText1($extrinsic_text1)
    {
        
        $this->extrinsic_text1 = $extrinsic_text1;
        return $this;
    }
    
    /**
     * Gets extrinsic_text2
     * @return string
     */
    public function getExtrinsicText2()
    {
        return $this->extrinsic_text2;
    }
  
    /**
     * Sets extrinsic_text2
     * @param string $extrinsic_text2 
     * @return $this
     */
    public function setExtrinsicText2($extrinsic_text2)
    {
        
        $this->extrinsic_text2 = $extrinsic_text2;
        return $this;
    }
    
    /**
     * Gets extrinsic_text3
     * @return string
     */
    public function getExtrinsicText3()
    {
        return $this->extrinsic_text3;
    }
  
    /**
     * Sets extrinsic_text3
     * @param string $extrinsic_text3 
     * @return $this
     */
    public function setExtrinsicText3($extrinsic_text3)
    {
        
        $this->extrinsic_text3 = $extrinsic_text3;
        return $this;
    }
    
    /**
     * Gets extrinsic_number1
     * @return int
     */
    public function getExtrinsicNumber1()
    {
        return $this->extrinsic_number1;
    }
  
    /**
     * Sets extrinsic_number1
     * @param int $extrinsic_number1 
     * @return $this
     */
    public function setExtrinsicNumber1($extrinsic_number1)
    {
        
        $this->extrinsic_number1 = $extrinsic_number1;
        return $this;
    }
    
    /**
     * Gets extrinsic_number2
     * @return int
     */
    public function getExtrinsicNumber2()
    {
        return $this->extrinsic_number2;
    }
  
    /**
     * Sets extrinsic_number2
     * @param int $extrinsic_number2 
     * @return $this
     */
    public function setExtrinsicNumber2($extrinsic_number2)
    {
        
        $this->extrinsic_number2 = $extrinsic_number2;
        return $this;
    }
    
    /**
     * Gets extrinsic_decimal1
     * @return double
     */
    public function getExtrinsicDecimal1()
    {
        return $this->extrinsic_decimal1;
    }
  
    /**
     * Sets extrinsic_decimal1
     * @param double $extrinsic_decimal1 
     * @return $this
     */
    public function setExtrinsicDecimal1($extrinsic_decimal1)
    {
        
        $this->extrinsic_decimal1 = $extrinsic_decimal1;
        return $this;
    }
    
    /**
     * Gets extrinsic_decimal2
     * @return double
     */
    public function getExtrinsicDecimal2()
    {
        return $this->extrinsic_decimal2;
    }
  
    /**
     * Sets extrinsic_decimal2
     * @param double $extrinsic_decimal2 
     * @return $this
     */
    public function setExtrinsicDecimal2($extrinsic_decimal2)
    {
        
        $this->extrinsic_decimal2 = $extrinsic_decimal2;
        return $this;
    }
    
    /**
     * Gets modify_date
     * @return \DateTime
     */
    public function getModifyDate()
    {
        return $this->modify_date;
    }
  
    /**
     * Sets modify_date
     * @param \DateTime $modify_date 
     * @return $this
     */
    public function setModifyDate($modify_date)
    {
        
        $this->modify_date = $modify_date;
        return $this;
    }
    
    /**
     * Gets oms_customer_id
     * @return int
     */
    public function getOmsCustomerId()
    {
        return $this->oms_customer_id;
    }
  
    /**
     * Sets oms_customer_id
     * @param int $oms_customer_id 
     * @return $this
     */
    public function setOmsCustomerId($oms_customer_id)
    {
        
        $this->oms_customer_id = $oms_customer_id;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Infoplus\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Infoplus\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
