<?php
/**
 * InvoiceWorksheet
 *
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Infoplus\Model;

use \ArrayAccess;
/**
 * InvoiceWorksheet Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Infoplus
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoiceWorksheet implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'id' => 'int',
        'create_date' => '\DateTime',
        'modify_date' => '\DateTime',
        'name' => 'string',
        'invoice_no' => 'string',
        'po_no' => 'string',
        'cost_center' => 'string',
        'description' => 'string',
        'notes' => 'string',
        'terms' => 'string',
        'special_instructions' => 'string',
        'total' => 'Number',
        'lob_id' => 'int',
        'customer_invoice_template_id' => 'int',
        'start_date' => '\DateTime',
        'end_date' => '\DateTime',
        'issue_date' => '\DateTime',
        'status' => 'string',
        'remit_to_attention' => 'string',
        'remit_to_company' => 'string',
        'remit_to_street' => 'string',
        'remit_to_street2' => 'string',
        'remit_to_street3' => 'string',
        'remit_to_city' => 'string',
        'remit_to_state' => 'string',
        'remit_to_zip' => 'string',
        'remit_to_country' => 'string',
        'remit_to_phone' => 'string',
        'remit_to_email' => 'string',
        'bill_to_attention' => 'string',
        'bill_to_company' => 'string',
        'bill_to_street' => 'string',
        'bill_to_street2' => 'string',
        'bill_to_street3' => 'string',
        'bill_to_city' => 'string',
        'bill_to_state' => 'string',
        'bill_to_zip' => 'string',
        'bill_to_country' => 'string',
        'bill_to_phone' => 'string',
        'bill_to_email' => 'string',
        'invoice_worksheet_line_item_list' => '\Infoplus\Model\InvoiceWorksheetLine[]',
        'custom_fields' => 'map[string,object]'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'id' => 'id',
        'create_date' => 'createDate',
        'modify_date' => 'modifyDate',
        'name' => 'name',
        'invoice_no' => 'invoiceNo',
        'po_no' => 'poNo',
        'cost_center' => 'costCenter',
        'description' => 'description',
        'notes' => 'notes',
        'terms' => 'terms',
        'special_instructions' => 'specialInstructions',
        'total' => 'total',
        'lob_id' => 'lobId',
        'customer_invoice_template_id' => 'customerInvoiceTemplateId',
        'start_date' => 'startDate',
        'end_date' => 'endDate',
        'issue_date' => 'issueDate',
        'status' => 'status',
        'remit_to_attention' => 'remitToAttention',
        'remit_to_company' => 'remitToCompany',
        'remit_to_street' => 'remitToStreet',
        'remit_to_street2' => 'remitToStreet2',
        'remit_to_street3' => 'remitToStreet3',
        'remit_to_city' => 'remitToCity',
        'remit_to_state' => 'remitToState',
        'remit_to_zip' => 'remitToZip',
        'remit_to_country' => 'remitToCountry',
        'remit_to_phone' => 'remitToPhone',
        'remit_to_email' => 'remitToEmail',
        'bill_to_attention' => 'billToAttention',
        'bill_to_company' => 'billToCompany',
        'bill_to_street' => 'billToStreet',
        'bill_to_street2' => 'billToStreet2',
        'bill_to_street3' => 'billToStreet3',
        'bill_to_city' => 'billToCity',
        'bill_to_state' => 'billToState',
        'bill_to_zip' => 'billToZip',
        'bill_to_country' => 'billToCountry',
        'bill_to_phone' => 'billToPhone',
        'bill_to_email' => 'billToEmail',
        'invoice_worksheet_line_item_list' => 'invoiceWorksheetLineItemList',
        'custom_fields' => 'customFields'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'id' => 'setId',
        'create_date' => 'setCreateDate',
        'modify_date' => 'setModifyDate',
        'name' => 'setName',
        'invoice_no' => 'setInvoiceNo',
        'po_no' => 'setPoNo',
        'cost_center' => 'setCostCenter',
        'description' => 'setDescription',
        'notes' => 'setNotes',
        'terms' => 'setTerms',
        'special_instructions' => 'setSpecialInstructions',
        'total' => 'setTotal',
        'lob_id' => 'setLobId',
        'customer_invoice_template_id' => 'setCustomerInvoiceTemplateId',
        'start_date' => 'setStartDate',
        'end_date' => 'setEndDate',
        'issue_date' => 'setIssueDate',
        'status' => 'setStatus',
        'remit_to_attention' => 'setRemitToAttention',
        'remit_to_company' => 'setRemitToCompany',
        'remit_to_street' => 'setRemitToStreet',
        'remit_to_street2' => 'setRemitToStreet2',
        'remit_to_street3' => 'setRemitToStreet3',
        'remit_to_city' => 'setRemitToCity',
        'remit_to_state' => 'setRemitToState',
        'remit_to_zip' => 'setRemitToZip',
        'remit_to_country' => 'setRemitToCountry',
        'remit_to_phone' => 'setRemitToPhone',
        'remit_to_email' => 'setRemitToEmail',
        'bill_to_attention' => 'setBillToAttention',
        'bill_to_company' => 'setBillToCompany',
        'bill_to_street' => 'setBillToStreet',
        'bill_to_street2' => 'setBillToStreet2',
        'bill_to_street3' => 'setBillToStreet3',
        'bill_to_city' => 'setBillToCity',
        'bill_to_state' => 'setBillToState',
        'bill_to_zip' => 'setBillToZip',
        'bill_to_country' => 'setBillToCountry',
        'bill_to_phone' => 'setBillToPhone',
        'bill_to_email' => 'setBillToEmail',
        'invoice_worksheet_line_item_list' => 'setInvoiceWorksheetLineItemList',
        'custom_fields' => 'setCustomFields'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'id' => 'getId',
        'create_date' => 'getCreateDate',
        'modify_date' => 'getModifyDate',
        'name' => 'getName',
        'invoice_no' => 'getInvoiceNo',
        'po_no' => 'getPoNo',
        'cost_center' => 'getCostCenter',
        'description' => 'getDescription',
        'notes' => 'getNotes',
        'terms' => 'getTerms',
        'special_instructions' => 'getSpecialInstructions',
        'total' => 'getTotal',
        'lob_id' => 'getLobId',
        'customer_invoice_template_id' => 'getCustomerInvoiceTemplateId',
        'start_date' => 'getStartDate',
        'end_date' => 'getEndDate',
        'issue_date' => 'getIssueDate',
        'status' => 'getStatus',
        'remit_to_attention' => 'getRemitToAttention',
        'remit_to_company' => 'getRemitToCompany',
        'remit_to_street' => 'getRemitToStreet',
        'remit_to_street2' => 'getRemitToStreet2',
        'remit_to_street3' => 'getRemitToStreet3',
        'remit_to_city' => 'getRemitToCity',
        'remit_to_state' => 'getRemitToState',
        'remit_to_zip' => 'getRemitToZip',
        'remit_to_country' => 'getRemitToCountry',
        'remit_to_phone' => 'getRemitToPhone',
        'remit_to_email' => 'getRemitToEmail',
        'bill_to_attention' => 'getBillToAttention',
        'bill_to_company' => 'getBillToCompany',
        'bill_to_street' => 'getBillToStreet',
        'bill_to_street2' => 'getBillToStreet2',
        'bill_to_street3' => 'getBillToStreet3',
        'bill_to_city' => 'getBillToCity',
        'bill_to_state' => 'getBillToState',
        'bill_to_zip' => 'getBillToZip',
        'bill_to_country' => 'getBillToCountry',
        'bill_to_phone' => 'getBillToPhone',
        'bill_to_email' => 'getBillToEmail',
        'invoice_worksheet_line_item_list' => 'getInvoiceWorksheetLineItemList',
        'custom_fields' => 'getCustomFields'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $id 
      * @var int
      */
    protected $id;
    
    /**
      * $create_date 
      * @var \DateTime
      */
    protected $create_date;
    
    /**
      * $modify_date 
      * @var \DateTime
      */
    protected $modify_date;
    
    /**
      * $name 
      * @var string
      */
    protected $name;
    
    /**
      * $invoice_no 
      * @var string
      */
    protected $invoice_no;
    
    /**
      * $po_no 
      * @var string
      */
    protected $po_no;
    
    /**
      * $cost_center 
      * @var string
      */
    protected $cost_center;
    
    /**
      * $description 
      * @var string
      */
    protected $description;
    
    /**
      * $notes 
      * @var string
      */
    protected $notes;
    
    /**
      * $terms 
      * @var string
      */
    protected $terms;
    
    /**
      * $special_instructions 
      * @var string
      */
    protected $special_instructions;
    
    /**
      * $total 
      * @var Number
      */
    protected $total;
    
    /**
      * $lob_id 
      * @var int
      */
    protected $lob_id;
    
    /**
      * $customer_invoice_template_id 
      * @var int
      */
    protected $customer_invoice_template_id;
    
    /**
      * $start_date 
      * @var \DateTime
      */
    protected $start_date;
    
    /**
      * $end_date 
      * @var \DateTime
      */
    protected $end_date;
    
    /**
      * $issue_date 
      * @var \DateTime
      */
    protected $issue_date;
    
    /**
      * $status 
      * @var string
      */
    protected $status;
    
    /**
      * $remit_to_attention 
      * @var string
      */
    protected $remit_to_attention;
    
    /**
      * $remit_to_company 
      * @var string
      */
    protected $remit_to_company;
    
    /**
      * $remit_to_street 
      * @var string
      */
    protected $remit_to_street;
    
    /**
      * $remit_to_street2 
      * @var string
      */
    protected $remit_to_street2;
    
    /**
      * $remit_to_street3 
      * @var string
      */
    protected $remit_to_street3;
    
    /**
      * $remit_to_city 
      * @var string
      */
    protected $remit_to_city;
    
    /**
      * $remit_to_state 
      * @var string
      */
    protected $remit_to_state;
    
    /**
      * $remit_to_zip 
      * @var string
      */
    protected $remit_to_zip;
    
    /**
      * $remit_to_country 
      * @var string
      */
    protected $remit_to_country;
    
    /**
      * $remit_to_phone 
      * @var string
      */
    protected $remit_to_phone;
    
    /**
      * $remit_to_email 
      * @var string
      */
    protected $remit_to_email;
    
    /**
      * $bill_to_attention 
      * @var string
      */
    protected $bill_to_attention;
    
    /**
      * $bill_to_company 
      * @var string
      */
    protected $bill_to_company;
    
    /**
      * $bill_to_street 
      * @var string
      */
    protected $bill_to_street;
    
    /**
      * $bill_to_street2 
      * @var string
      */
    protected $bill_to_street2;
    
    /**
      * $bill_to_street3 
      * @var string
      */
    protected $bill_to_street3;
    
    /**
      * $bill_to_city 
      * @var string
      */
    protected $bill_to_city;
    
    /**
      * $bill_to_state 
      * @var string
      */
    protected $bill_to_state;
    
    /**
      * $bill_to_zip 
      * @var string
      */
    protected $bill_to_zip;
    
    /**
      * $bill_to_country 
      * @var string
      */
    protected $bill_to_country;
    
    /**
      * $bill_to_phone 
      * @var string
      */
    protected $bill_to_phone;
    
    /**
      * $bill_to_email 
      * @var string
      */
    protected $bill_to_email;
    
    /**
      * $invoice_worksheet_line_item_list 
      * @var \Infoplus\Model\InvoiceWorksheetLine[]
      */
    protected $invoice_worksheet_line_item_list;
    
    /**
      * $custom_fields 
      * @var map[string,object]
      */
    protected $custom_fields;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->id = $data["id"];
            $this->create_date = $data["create_date"];
            $this->modify_date = $data["modify_date"];
            $this->name = $data["name"];
            $this->invoice_no = $data["invoice_no"];
            $this->po_no = $data["po_no"];
            $this->cost_center = $data["cost_center"];
            $this->description = $data["description"];
            $this->notes = $data["notes"];
            $this->terms = $data["terms"];
            $this->special_instructions = $data["special_instructions"];
            $this->total = $data["total"];
            $this->lob_id = $data["lob_id"];
            $this->customer_invoice_template_id = $data["customer_invoice_template_id"];
            $this->start_date = $data["start_date"];
            $this->end_date = $data["end_date"];
            $this->issue_date = $data["issue_date"];
            $this->status = $data["status"];
            $this->remit_to_attention = $data["remit_to_attention"];
            $this->remit_to_company = $data["remit_to_company"];
            $this->remit_to_street = $data["remit_to_street"];
            $this->remit_to_street2 = $data["remit_to_street2"];
            $this->remit_to_street3 = $data["remit_to_street3"];
            $this->remit_to_city = $data["remit_to_city"];
            $this->remit_to_state = $data["remit_to_state"];
            $this->remit_to_zip = $data["remit_to_zip"];
            $this->remit_to_country = $data["remit_to_country"];
            $this->remit_to_phone = $data["remit_to_phone"];
            $this->remit_to_email = $data["remit_to_email"];
            $this->bill_to_attention = $data["bill_to_attention"];
            $this->bill_to_company = $data["bill_to_company"];
            $this->bill_to_street = $data["bill_to_street"];
            $this->bill_to_street2 = $data["bill_to_street2"];
            $this->bill_to_street3 = $data["bill_to_street3"];
            $this->bill_to_city = $data["bill_to_city"];
            $this->bill_to_state = $data["bill_to_state"];
            $this->bill_to_zip = $data["bill_to_zip"];
            $this->bill_to_country = $data["bill_to_country"];
            $this->bill_to_phone = $data["bill_to_phone"];
            $this->bill_to_email = $data["bill_to_email"];
            $this->invoice_worksheet_line_item_list = $data["invoice_worksheet_line_item_list"];
            $this->custom_fields = $data["custom_fields"];
        }
    }
    
    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
  
    /**
     * Sets id
     * @param int $id 
     * @return $this
     */
    public function setId($id)
    {
        
        $this->id = $id;
        return $this;
    }
    
    /**
     * Gets create_date
     * @return \DateTime
     */
    public function getCreateDate()
    {
        return $this->create_date;
    }
  
    /**
     * Sets create_date
     * @param \DateTime $create_date 
     * @return $this
     */
    public function setCreateDate($create_date)
    {
        
        $this->create_date = $create_date;
        return $this;
    }
    
    /**
     * Gets modify_date
     * @return \DateTime
     */
    public function getModifyDate()
    {
        return $this->modify_date;
    }
  
    /**
     * Sets modify_date
     * @param \DateTime $modify_date 
     * @return $this
     */
    public function setModifyDate($modify_date)
    {
        
        $this->modify_date = $modify_date;
        return $this;
    }
    
    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
  
    /**
     * Sets name
     * @param string $name 
     * @return $this
     */
    public function setName($name)
    {
        
        $this->name = $name;
        return $this;
    }
    
    /**
     * Gets invoice_no
     * @return string
     */
    public function getInvoiceNo()
    {
        return $this->invoice_no;
    }
  
    /**
     * Sets invoice_no
     * @param string $invoice_no 
     * @return $this
     */
    public function setInvoiceNo($invoice_no)
    {
        
        $this->invoice_no = $invoice_no;
        return $this;
    }
    
    /**
     * Gets po_no
     * @return string
     */
    public function getPoNo()
    {
        return $this->po_no;
    }
  
    /**
     * Sets po_no
     * @param string $po_no 
     * @return $this
     */
    public function setPoNo($po_no)
    {
        
        $this->po_no = $po_no;
        return $this;
    }
    
    /**
     * Gets cost_center
     * @return string
     */
    public function getCostCenter()
    {
        return $this->cost_center;
    }
  
    /**
     * Sets cost_center
     * @param string $cost_center 
     * @return $this
     */
    public function setCostCenter($cost_center)
    {
        
        $this->cost_center = $cost_center;
        return $this;
    }
    
    /**
     * Gets description
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }
  
    /**
     * Sets description
     * @param string $description 
     * @return $this
     */
    public function setDescription($description)
    {
        
        $this->description = $description;
        return $this;
    }
    
    /**
     * Gets notes
     * @return string
     */
    public function getNotes()
    {
        return $this->notes;
    }
  
    /**
     * Sets notes
     * @param string $notes 
     * @return $this
     */
    public function setNotes($notes)
    {
        
        $this->notes = $notes;
        return $this;
    }
    
    /**
     * Gets terms
     * @return string
     */
    public function getTerms()
    {
        return $this->terms;
    }
  
    /**
     * Sets terms
     * @param string $terms 
     * @return $this
     */
    public function setTerms($terms)
    {
        
        $this->terms = $terms;
        return $this;
    }
    
    /**
     * Gets special_instructions
     * @return string
     */
    public function getSpecialInstructions()
    {
        return $this->special_instructions;
    }
  
    /**
     * Sets special_instructions
     * @param string $special_instructions 
     * @return $this
     */
    public function setSpecialInstructions($special_instructions)
    {
        
        $this->special_instructions = $special_instructions;
        return $this;
    }
    
    /**
     * Gets total
     * @return Number
     */
    public function getTotal()
    {
        return $this->total;
    }
  
    /**
     * Sets total
     * @param Number $total 
     * @return $this
     */
    public function setTotal($total)
    {
        
        $this->total = $total;
        return $this;
    }
    
    /**
     * Gets lob_id
     * @return int
     */
    public function getLobId()
    {
        return $this->lob_id;
    }
  
    /**
     * Sets lob_id
     * @param int $lob_id 
     * @return $this
     */
    public function setLobId($lob_id)
    {
        
        $this->lob_id = $lob_id;
        return $this;
    }
    
    /**
     * Gets customer_invoice_template_id
     * @return int
     */
    public function getCustomerInvoiceTemplateId()
    {
        return $this->customer_invoice_template_id;
    }
  
    /**
     * Sets customer_invoice_template_id
     * @param int $customer_invoice_template_id 
     * @return $this
     */
    public function setCustomerInvoiceTemplateId($customer_invoice_template_id)
    {
        
        $this->customer_invoice_template_id = $customer_invoice_template_id;
        return $this;
    }
    
    /**
     * Gets start_date
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->start_date;
    }
  
    /**
     * Sets start_date
     * @param \DateTime $start_date 
     * @return $this
     */
    public function setStartDate($start_date)
    {
        
        $this->start_date = $start_date;
        return $this;
    }
    
    /**
     * Gets end_date
     * @return \DateTime
     */
    public function getEndDate()
    {
        return $this->end_date;
    }
  
    /**
     * Sets end_date
     * @param \DateTime $end_date 
     * @return $this
     */
    public function setEndDate($end_date)
    {
        
        $this->end_date = $end_date;
        return $this;
    }
    
    /**
     * Gets issue_date
     * @return \DateTime
     */
    public function getIssueDate()
    {
        return $this->issue_date;
    }
  
    /**
     * Sets issue_date
     * @param \DateTime $issue_date 
     * @return $this
     */
    public function setIssueDate($issue_date)
    {
        
        $this->issue_date = $issue_date;
        return $this;
    }
    
    /**
     * Gets status
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }
  
    /**
     * Sets status
     * @param string $status 
     * @return $this
     */
    public function setStatus($status)
    {
        
        $this->status = $status;
        return $this;
    }
    
    /**
     * Gets remit_to_attention
     * @return string
     */
    public function getRemitToAttention()
    {
        return $this->remit_to_attention;
    }
  
    /**
     * Sets remit_to_attention
     * @param string $remit_to_attention 
     * @return $this
     */
    public function setRemitToAttention($remit_to_attention)
    {
        
        $this->remit_to_attention = $remit_to_attention;
        return $this;
    }
    
    /**
     * Gets remit_to_company
     * @return string
     */
    public function getRemitToCompany()
    {
        return $this->remit_to_company;
    }
  
    /**
     * Sets remit_to_company
     * @param string $remit_to_company 
     * @return $this
     */
    public function setRemitToCompany($remit_to_company)
    {
        
        $this->remit_to_company = $remit_to_company;
        return $this;
    }
    
    /**
     * Gets remit_to_street
     * @return string
     */
    public function getRemitToStreet()
    {
        return $this->remit_to_street;
    }
  
    /**
     * Sets remit_to_street
     * @param string $remit_to_street 
     * @return $this
     */
    public function setRemitToStreet($remit_to_street)
    {
        
        $this->remit_to_street = $remit_to_street;
        return $this;
    }
    
    /**
     * Gets remit_to_street2
     * @return string
     */
    public function getRemitToStreet2()
    {
        return $this->remit_to_street2;
    }
  
    /**
     * Sets remit_to_street2
     * @param string $remit_to_street2 
     * @return $this
     */
    public function setRemitToStreet2($remit_to_street2)
    {
        
        $this->remit_to_street2 = $remit_to_street2;
        return $this;
    }
    
    /**
     * Gets remit_to_street3
     * @return string
     */
    public function getRemitToStreet3()
    {
        return $this->remit_to_street3;
    }
  
    /**
     * Sets remit_to_street3
     * @param string $remit_to_street3 
     * @return $this
     */
    public function setRemitToStreet3($remit_to_street3)
    {
        
        $this->remit_to_street3 = $remit_to_street3;
        return $this;
    }
    
    /**
     * Gets remit_to_city
     * @return string
     */
    public function getRemitToCity()
    {
        return $this->remit_to_city;
    }
  
    /**
     * Sets remit_to_city
     * @param string $remit_to_city 
     * @return $this
     */
    public function setRemitToCity($remit_to_city)
    {
        
        $this->remit_to_city = $remit_to_city;
        return $this;
    }
    
    /**
     * Gets remit_to_state
     * @return string
     */
    public function getRemitToState()
    {
        return $this->remit_to_state;
    }
  
    /**
     * Sets remit_to_state
     * @param string $remit_to_state 
     * @return $this
     */
    public function setRemitToState($remit_to_state)
    {
        
        $this->remit_to_state = $remit_to_state;
        return $this;
    }
    
    /**
     * Gets remit_to_zip
     * @return string
     */
    public function getRemitToZip()
    {
        return $this->remit_to_zip;
    }
  
    /**
     * Sets remit_to_zip
     * @param string $remit_to_zip 
     * @return $this
     */
    public function setRemitToZip($remit_to_zip)
    {
        
        $this->remit_to_zip = $remit_to_zip;
        return $this;
    }
    
    /**
     * Gets remit_to_country
     * @return string
     */
    public function getRemitToCountry()
    {
        return $this->remit_to_country;
    }
  
    /**
     * Sets remit_to_country
     * @param string $remit_to_country 
     * @return $this
     */
    public function setRemitToCountry($remit_to_country)
    {
        
        $this->remit_to_country = $remit_to_country;
        return $this;
    }
    
    /**
     * Gets remit_to_phone
     * @return string
     */
    public function getRemitToPhone()
    {
        return $this->remit_to_phone;
    }
  
    /**
     * Sets remit_to_phone
     * @param string $remit_to_phone 
     * @return $this
     */
    public function setRemitToPhone($remit_to_phone)
    {
        
        $this->remit_to_phone = $remit_to_phone;
        return $this;
    }
    
    /**
     * Gets remit_to_email
     * @return string
     */
    public function getRemitToEmail()
    {
        return $this->remit_to_email;
    }
  
    /**
     * Sets remit_to_email
     * @param string $remit_to_email 
     * @return $this
     */
    public function setRemitToEmail($remit_to_email)
    {
        
        $this->remit_to_email = $remit_to_email;
        return $this;
    }
    
    /**
     * Gets bill_to_attention
     * @return string
     */
    public function getBillToAttention()
    {
        return $this->bill_to_attention;
    }
  
    /**
     * Sets bill_to_attention
     * @param string $bill_to_attention 
     * @return $this
     */
    public function setBillToAttention($bill_to_attention)
    {
        
        $this->bill_to_attention = $bill_to_attention;
        return $this;
    }
    
    /**
     * Gets bill_to_company
     * @return string
     */
    public function getBillToCompany()
    {
        return $this->bill_to_company;
    }
  
    /**
     * Sets bill_to_company
     * @param string $bill_to_company 
     * @return $this
     */
    public function setBillToCompany($bill_to_company)
    {
        
        $this->bill_to_company = $bill_to_company;
        return $this;
    }
    
    /**
     * Gets bill_to_street
     * @return string
     */
    public function getBillToStreet()
    {
        return $this->bill_to_street;
    }
  
    /**
     * Sets bill_to_street
     * @param string $bill_to_street 
     * @return $this
     */
    public function setBillToStreet($bill_to_street)
    {
        
        $this->bill_to_street = $bill_to_street;
        return $this;
    }
    
    /**
     * Gets bill_to_street2
     * @return string
     */
    public function getBillToStreet2()
    {
        return $this->bill_to_street2;
    }
  
    /**
     * Sets bill_to_street2
     * @param string $bill_to_street2 
     * @return $this
     */
    public function setBillToStreet2($bill_to_street2)
    {
        
        $this->bill_to_street2 = $bill_to_street2;
        return $this;
    }
    
    /**
     * Gets bill_to_street3
     * @return string
     */
    public function getBillToStreet3()
    {
        return $this->bill_to_street3;
    }
  
    /**
     * Sets bill_to_street3
     * @param string $bill_to_street3 
     * @return $this
     */
    public function setBillToStreet3($bill_to_street3)
    {
        
        $this->bill_to_street3 = $bill_to_street3;
        return $this;
    }
    
    /**
     * Gets bill_to_city
     * @return string
     */
    public function getBillToCity()
    {
        return $this->bill_to_city;
    }
  
    /**
     * Sets bill_to_city
     * @param string $bill_to_city 
     * @return $this
     */
    public function setBillToCity($bill_to_city)
    {
        
        $this->bill_to_city = $bill_to_city;
        return $this;
    }
    
    /**
     * Gets bill_to_state
     * @return string
     */
    public function getBillToState()
    {
        return $this->bill_to_state;
    }
  
    /**
     * Sets bill_to_state
     * @param string $bill_to_state 
     * @return $this
     */
    public function setBillToState($bill_to_state)
    {
        
        $this->bill_to_state = $bill_to_state;
        return $this;
    }
    
    /**
     * Gets bill_to_zip
     * @return string
     */
    public function getBillToZip()
    {
        return $this->bill_to_zip;
    }
  
    /**
     * Sets bill_to_zip
     * @param string $bill_to_zip 
     * @return $this
     */
    public function setBillToZip($bill_to_zip)
    {
        
        $this->bill_to_zip = $bill_to_zip;
        return $this;
    }
    
    /**
     * Gets bill_to_country
     * @return string
     */
    public function getBillToCountry()
    {
        return $this->bill_to_country;
    }
  
    /**
     * Sets bill_to_country
     * @param string $bill_to_country 
     * @return $this
     */
    public function setBillToCountry($bill_to_country)
    {
        
        $this->bill_to_country = $bill_to_country;
        return $this;
    }
    
    /**
     * Gets bill_to_phone
     * @return string
     */
    public function getBillToPhone()
    {
        return $this->bill_to_phone;
    }
  
    /**
     * Sets bill_to_phone
     * @param string $bill_to_phone 
     * @return $this
     */
    public function setBillToPhone($bill_to_phone)
    {
        
        $this->bill_to_phone = $bill_to_phone;
        return $this;
    }
    
    /**
     * Gets bill_to_email
     * @return string
     */
    public function getBillToEmail()
    {
        return $this->bill_to_email;
    }
  
    /**
     * Sets bill_to_email
     * @param string $bill_to_email 
     * @return $this
     */
    public function setBillToEmail($bill_to_email)
    {
        
        $this->bill_to_email = $bill_to_email;
        return $this;
    }
    
    /**
     * Gets invoice_worksheet_line_item_list
     * @return \Infoplus\Model\InvoiceWorksheetLine[]
     */
    public function getInvoiceWorksheetLineItemList()
    {
        return $this->invoice_worksheet_line_item_list;
    }
  
    /**
     * Sets invoice_worksheet_line_item_list
     * @param \Infoplus\Model\InvoiceWorksheetLine[] $invoice_worksheet_line_item_list 
     * @return $this
     */
    public function setInvoiceWorksheetLineItemList($invoice_worksheet_line_item_list)
    {
        
        $this->invoice_worksheet_line_item_list = $invoice_worksheet_line_item_list;
        return $this;
    }
    
    /**
     * Gets custom_fields
     * @return map[string,object]
     */
    public function getCustomFields()
    {
        return $this->custom_fields;
    }
  
    /**
     * Sets custom_fields
     * @param map[string,object] $custom_fields 
     * @return $this
     */
    public function setCustomFields($custom_fields)
    {
        
        $this->custom_fields = $custom_fields;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Infoplus\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Infoplus\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
