<?php
/**
 * ReceivingWorksheetLineItem
 *
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Infoplus\Model;

use \ArrayAccess;
/**
 * ReceivingWorksheetLineItem Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Infoplus
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReceivingWorksheetLineItem implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'sku' => 'string',
        'sku2' => 'string',
        'full_description' => 'string',
        'ordered_qty' => 'int',
        'prev_received_qty' => 'int',
        'unreceived_qty' => 'int',
        'receiving_qty' => 'int',
        'unit_code' => 'string',
        'wrap_code' => 'string',
        'units_per_wrap' => 'int',
        'units_per_case' => 'int',
        'cases_per_pallet' => 'int',
        'weight_per_wrap' => 'Number',
        'weight_per_case' => 'Number',
        'production_lot' => 'string',
        'product_id_tag' => 'string',
        'revision_date' => 'string',
        'origin' => 'string',
        'carton_length' => 'Number',
        'carton_width' => 'Number',
        'carton_height' => 'Number',
        'put_away_plans' => '\Infoplus\Model\ReceivingWorksheetPutAwayPlan[]',
        'quantity' => 'int',
        'custom_fields' => 'map[string,object]'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'sku' => 'sku',
        'sku2' => 'sku2',
        'full_description' => 'fullDescription',
        'ordered_qty' => 'orderedQty',
        'prev_received_qty' => 'prevReceivedQty',
        'unreceived_qty' => 'unreceivedQty',
        'receiving_qty' => 'receivingQty',
        'unit_code' => 'unitCode',
        'wrap_code' => 'wrapCode',
        'units_per_wrap' => 'unitsPerWrap',
        'units_per_case' => 'unitsPerCase',
        'cases_per_pallet' => 'casesPerPallet',
        'weight_per_wrap' => 'weightPerWrap',
        'weight_per_case' => 'weightPerCase',
        'production_lot' => 'productionLot',
        'product_id_tag' => 'productIdTag',
        'revision_date' => 'revisionDate',
        'origin' => 'origin',
        'carton_length' => 'cartonLength',
        'carton_width' => 'cartonWidth',
        'carton_height' => 'cartonHeight',
        'put_away_plans' => 'putAwayPlans',
        'quantity' => 'quantity',
        'custom_fields' => 'customFields'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'sku' => 'setSku',
        'sku2' => 'setSku2',
        'full_description' => 'setFullDescription',
        'ordered_qty' => 'setOrderedQty',
        'prev_received_qty' => 'setPrevReceivedQty',
        'unreceived_qty' => 'setUnreceivedQty',
        'receiving_qty' => 'setReceivingQty',
        'unit_code' => 'setUnitCode',
        'wrap_code' => 'setWrapCode',
        'units_per_wrap' => 'setUnitsPerWrap',
        'units_per_case' => 'setUnitsPerCase',
        'cases_per_pallet' => 'setCasesPerPallet',
        'weight_per_wrap' => 'setWeightPerWrap',
        'weight_per_case' => 'setWeightPerCase',
        'production_lot' => 'setProductionLot',
        'product_id_tag' => 'setProductIdTag',
        'revision_date' => 'setRevisionDate',
        'origin' => 'setOrigin',
        'carton_length' => 'setCartonLength',
        'carton_width' => 'setCartonWidth',
        'carton_height' => 'setCartonHeight',
        'put_away_plans' => 'setPutAwayPlans',
        'quantity' => 'setQuantity',
        'custom_fields' => 'setCustomFields'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'sku' => 'getSku',
        'sku2' => 'getSku2',
        'full_description' => 'getFullDescription',
        'ordered_qty' => 'getOrderedQty',
        'prev_received_qty' => 'getPrevReceivedQty',
        'unreceived_qty' => 'getUnreceivedQty',
        'receiving_qty' => 'getReceivingQty',
        'unit_code' => 'getUnitCode',
        'wrap_code' => 'getWrapCode',
        'units_per_wrap' => 'getUnitsPerWrap',
        'units_per_case' => 'getUnitsPerCase',
        'cases_per_pallet' => 'getCasesPerPallet',
        'weight_per_wrap' => 'getWeightPerWrap',
        'weight_per_case' => 'getWeightPerCase',
        'production_lot' => 'getProductionLot',
        'product_id_tag' => 'getProductIdTag',
        'revision_date' => 'getRevisionDate',
        'origin' => 'getOrigin',
        'carton_length' => 'getCartonLength',
        'carton_width' => 'getCartonWidth',
        'carton_height' => 'getCartonHeight',
        'put_away_plans' => 'getPutAwayPlans',
        'quantity' => 'getQuantity',
        'custom_fields' => 'getCustomFields'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $sku 
      * @var string
      */
    protected $sku;
    
    /**
      * $sku2 
      * @var string
      */
    protected $sku2;
    
    /**
      * $full_description 
      * @var string
      */
    protected $full_description;
    
    /**
      * $ordered_qty 
      * @var int
      */
    protected $ordered_qty;
    
    /**
      * $prev_received_qty 
      * @var int
      */
    protected $prev_received_qty;
    
    /**
      * $unreceived_qty 
      * @var int
      */
    protected $unreceived_qty;
    
    /**
      * $receiving_qty 
      * @var int
      */
    protected $receiving_qty;
    
    /**
      * $unit_code 
      * @var string
      */
    protected $unit_code;
    
    /**
      * $wrap_code 
      * @var string
      */
    protected $wrap_code;
    
    /**
      * $units_per_wrap 
      * @var int
      */
    protected $units_per_wrap;
    
    /**
      * $units_per_case 
      * @var int
      */
    protected $units_per_case;
    
    /**
      * $cases_per_pallet 
      * @var int
      */
    protected $cases_per_pallet;
    
    /**
      * $weight_per_wrap 
      * @var Number
      */
    protected $weight_per_wrap;
    
    /**
      * $weight_per_case 
      * @var Number
      */
    protected $weight_per_case;
    
    /**
      * $production_lot 
      * @var string
      */
    protected $production_lot;
    
    /**
      * $product_id_tag 
      * @var string
      */
    protected $product_id_tag;
    
    /**
      * $revision_date 
      * @var string
      */
    protected $revision_date;
    
    /**
      * $origin 
      * @var string
      */
    protected $origin;
    
    /**
      * $carton_length 
      * @var Number
      */
    protected $carton_length;
    
    /**
      * $carton_width 
      * @var Number
      */
    protected $carton_width;
    
    /**
      * $carton_height 
      * @var Number
      */
    protected $carton_height;
    
    /**
      * $put_away_plans 
      * @var \Infoplus\Model\ReceivingWorksheetPutAwayPlan[]
      */
    protected $put_away_plans;
    
    /**
      * $quantity 
      * @var int
      */
    protected $quantity;
    
    /**
      * $custom_fields 
      * @var map[string,object]
      */
    protected $custom_fields;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->sku = $data["sku"];
            $this->sku2 = $data["sku2"];
            $this->full_description = $data["full_description"];
            $this->ordered_qty = $data["ordered_qty"];
            $this->prev_received_qty = $data["prev_received_qty"];
            $this->unreceived_qty = $data["unreceived_qty"];
            $this->receiving_qty = $data["receiving_qty"];
            $this->unit_code = $data["unit_code"];
            $this->wrap_code = $data["wrap_code"];
            $this->units_per_wrap = $data["units_per_wrap"];
            $this->units_per_case = $data["units_per_case"];
            $this->cases_per_pallet = $data["cases_per_pallet"];
            $this->weight_per_wrap = $data["weight_per_wrap"];
            $this->weight_per_case = $data["weight_per_case"];
            $this->production_lot = $data["production_lot"];
            $this->product_id_tag = $data["product_id_tag"];
            $this->revision_date = $data["revision_date"];
            $this->origin = $data["origin"];
            $this->carton_length = $data["carton_length"];
            $this->carton_width = $data["carton_width"];
            $this->carton_height = $data["carton_height"];
            $this->put_away_plans = $data["put_away_plans"];
            $this->quantity = $data["quantity"];
            $this->custom_fields = $data["custom_fields"];
        }
    }
    
    /**
     * Gets sku
     * @return string
     */
    public function getSku()
    {
        return $this->sku;
    }
  
    /**
     * Sets sku
     * @param string $sku 
     * @return $this
     */
    public function setSku($sku)
    {
        
        $this->sku = $sku;
        return $this;
    }
    
    /**
     * Gets sku2
     * @return string
     */
    public function getSku2()
    {
        return $this->sku2;
    }
  
    /**
     * Sets sku2
     * @param string $sku2 
     * @return $this
     */
    public function setSku2($sku2)
    {
        
        $this->sku2 = $sku2;
        return $this;
    }
    
    /**
     * Gets full_description
     * @return string
     */
    public function getFullDescription()
    {
        return $this->full_description;
    }
  
    /**
     * Sets full_description
     * @param string $full_description 
     * @return $this
     */
    public function setFullDescription($full_description)
    {
        
        $this->full_description = $full_description;
        return $this;
    }
    
    /**
     * Gets ordered_qty
     * @return int
     */
    public function getOrderedQty()
    {
        return $this->ordered_qty;
    }
  
    /**
     * Sets ordered_qty
     * @param int $ordered_qty 
     * @return $this
     */
    public function setOrderedQty($ordered_qty)
    {
        
        $this->ordered_qty = $ordered_qty;
        return $this;
    }
    
    /**
     * Gets prev_received_qty
     * @return int
     */
    public function getPrevReceivedQty()
    {
        return $this->prev_received_qty;
    }
  
    /**
     * Sets prev_received_qty
     * @param int $prev_received_qty 
     * @return $this
     */
    public function setPrevReceivedQty($prev_received_qty)
    {
        
        $this->prev_received_qty = $prev_received_qty;
        return $this;
    }
    
    /**
     * Gets unreceived_qty
     * @return int
     */
    public function getUnreceivedQty()
    {
        return $this->unreceived_qty;
    }
  
    /**
     * Sets unreceived_qty
     * @param int $unreceived_qty 
     * @return $this
     */
    public function setUnreceivedQty($unreceived_qty)
    {
        
        $this->unreceived_qty = $unreceived_qty;
        return $this;
    }
    
    /**
     * Gets receiving_qty
     * @return int
     */
    public function getReceivingQty()
    {
        return $this->receiving_qty;
    }
  
    /**
     * Sets receiving_qty
     * @param int $receiving_qty 
     * @return $this
     */
    public function setReceivingQty($receiving_qty)
    {
        
        $this->receiving_qty = $receiving_qty;
        return $this;
    }
    
    /**
     * Gets unit_code
     * @return string
     */
    public function getUnitCode()
    {
        return $this->unit_code;
    }
  
    /**
     * Sets unit_code
     * @param string $unit_code 
     * @return $this
     */
    public function setUnitCode($unit_code)
    {
        
        $this->unit_code = $unit_code;
        return $this;
    }
    
    /**
     * Gets wrap_code
     * @return string
     */
    public function getWrapCode()
    {
        return $this->wrap_code;
    }
  
    /**
     * Sets wrap_code
     * @param string $wrap_code 
     * @return $this
     */
    public function setWrapCode($wrap_code)
    {
        
        $this->wrap_code = $wrap_code;
        return $this;
    }
    
    /**
     * Gets units_per_wrap
     * @return int
     */
    public function getUnitsPerWrap()
    {
        return $this->units_per_wrap;
    }
  
    /**
     * Sets units_per_wrap
     * @param int $units_per_wrap 
     * @return $this
     */
    public function setUnitsPerWrap($units_per_wrap)
    {
        
        $this->units_per_wrap = $units_per_wrap;
        return $this;
    }
    
    /**
     * Gets units_per_case
     * @return int
     */
    public function getUnitsPerCase()
    {
        return $this->units_per_case;
    }
  
    /**
     * Sets units_per_case
     * @param int $units_per_case 
     * @return $this
     */
    public function setUnitsPerCase($units_per_case)
    {
        
        $this->units_per_case = $units_per_case;
        return $this;
    }
    
    /**
     * Gets cases_per_pallet
     * @return int
     */
    public function getCasesPerPallet()
    {
        return $this->cases_per_pallet;
    }
  
    /**
     * Sets cases_per_pallet
     * @param int $cases_per_pallet 
     * @return $this
     */
    public function setCasesPerPallet($cases_per_pallet)
    {
        
        $this->cases_per_pallet = $cases_per_pallet;
        return $this;
    }
    
    /**
     * Gets weight_per_wrap
     * @return Number
     */
    public function getWeightPerWrap()
    {
        return $this->weight_per_wrap;
    }
  
    /**
     * Sets weight_per_wrap
     * @param Number $weight_per_wrap 
     * @return $this
     */
    public function setWeightPerWrap($weight_per_wrap)
    {
        
        $this->weight_per_wrap = $weight_per_wrap;
        return $this;
    }
    
    /**
     * Gets weight_per_case
     * @return Number
     */
    public function getWeightPerCase()
    {
        return $this->weight_per_case;
    }
  
    /**
     * Sets weight_per_case
     * @param Number $weight_per_case 
     * @return $this
     */
    public function setWeightPerCase($weight_per_case)
    {
        
        $this->weight_per_case = $weight_per_case;
        return $this;
    }
    
    /**
     * Gets production_lot
     * @return string
     */
    public function getProductionLot()
    {
        return $this->production_lot;
    }
  
    /**
     * Sets production_lot
     * @param string $production_lot 
     * @return $this
     */
    public function setProductionLot($production_lot)
    {
        
        $this->production_lot = $production_lot;
        return $this;
    }
    
    /**
     * Gets product_id_tag
     * @return string
     */
    public function getProductIdTag()
    {
        return $this->product_id_tag;
    }
  
    /**
     * Sets product_id_tag
     * @param string $product_id_tag 
     * @return $this
     */
    public function setProductIdTag($product_id_tag)
    {
        
        $this->product_id_tag = $product_id_tag;
        return $this;
    }
    
    /**
     * Gets revision_date
     * @return string
     */
    public function getRevisionDate()
    {
        return $this->revision_date;
    }
  
    /**
     * Sets revision_date
     * @param string $revision_date 
     * @return $this
     */
    public function setRevisionDate($revision_date)
    {
        
        $this->revision_date = $revision_date;
        return $this;
    }
    
    /**
     * Gets origin
     * @return string
     */
    public function getOrigin()
    {
        return $this->origin;
    }
  
    /**
     * Sets origin
     * @param string $origin 
     * @return $this
     */
    public function setOrigin($origin)
    {
        
        $this->origin = $origin;
        return $this;
    }
    
    /**
     * Gets carton_length
     * @return Number
     */
    public function getCartonLength()
    {
        return $this->carton_length;
    }
  
    /**
     * Sets carton_length
     * @param Number $carton_length 
     * @return $this
     */
    public function setCartonLength($carton_length)
    {
        
        $this->carton_length = $carton_length;
        return $this;
    }
    
    /**
     * Gets carton_width
     * @return Number
     */
    public function getCartonWidth()
    {
        return $this->carton_width;
    }
  
    /**
     * Sets carton_width
     * @param Number $carton_width 
     * @return $this
     */
    public function setCartonWidth($carton_width)
    {
        
        $this->carton_width = $carton_width;
        return $this;
    }
    
    /**
     * Gets carton_height
     * @return Number
     */
    public function getCartonHeight()
    {
        return $this->carton_height;
    }
  
    /**
     * Sets carton_height
     * @param Number $carton_height 
     * @return $this
     */
    public function setCartonHeight($carton_height)
    {
        
        $this->carton_height = $carton_height;
        return $this;
    }
    
    /**
     * Gets put_away_plans
     * @return \Infoplus\Model\ReceivingWorksheetPutAwayPlan[]
     */
    public function getPutAwayPlans()
    {
        return $this->put_away_plans;
    }
  
    /**
     * Sets put_away_plans
     * @param \Infoplus\Model\ReceivingWorksheetPutAwayPlan[] $put_away_plans 
     * @return $this
     */
    public function setPutAwayPlans($put_away_plans)
    {
        
        $this->put_away_plans = $put_away_plans;
        return $this;
    }
    
    /**
     * Gets quantity
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }
  
    /**
     * Sets quantity
     * @param int $quantity 
     * @return $this
     */
    public function setQuantity($quantity)
    {
        
        $this->quantity = $quantity;
        return $this;
    }
    
    /**
     * Gets custom_fields
     * @return map[string,object]
     */
    public function getCustomFields()
    {
        return $this->custom_fields;
    }
  
    /**
     * Sets custom_fields
     * @param map[string,object] $custom_fields 
     * @return $this
     */
    public function setCustomFields($custom_fields)
    {
        
        $this->custom_fields = $custom_fields;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Infoplus\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Infoplus\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
