<?php
/**
 * CustomerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Infoplus;

/**
 * CustomerTest Class Doc Comment
 *
 * @category    Class */
// * @description Customer
/**
 * @package     Infoplus
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Customer"
     */
    public function testCustomer()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "lob_id"
     */
    public function testPropertyLobId()
    {
    }

    /**
     * Test attribute "customer_no"
     */
    public function testPropertyCustomerNo()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "attention"
     */
    public function testPropertyAttention()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "street2"
     */
    public function testPropertyStreet2()
    {
    }

    /**
     * Test attribute "street3_province"
     */
    public function testPropertyStreet3Province()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "zip_code"
     */
    public function testPropertyZipCode()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "fax"
     */
    public function testPropertyFax()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "boss_branch"
     */
    public function testPropertyBossBranch()
    {
    }

    /**
     * Test attribute "package_carrier_id"
     */
    public function testPropertyPackageCarrierId()
    {
    }

    /**
     * Test attribute "truck_carrier_id"
     */
    public function testPropertyTruckCarrierId()
    {
    }

    /**
     * Test attribute "weight_break"
     */
    public function testPropertyWeightBreak()
    {
    }

    /**
     * Test attribute "sector"
     */
    public function testPropertySector()
    {
    }

    /**
     * Test attribute "division"
     */
    public function testPropertyDivision()
    {
    }

    /**
     * Test attribute "cost_center"
     */
    public function testPropertyCostCenter()
    {
    }

    /**
     * Test attribute "county"
     */
    public function testPropertyCounty()
    {
    }

    /**
     * Test attribute "area"
     */
    public function testPropertyArea()
    {
    }

    /**
     * Test attribute "customer_type"
     */
    public function testPropertyCustomerType()
    {
    }

    /**
     * Test attribute "mass_level"
     */
    public function testPropertyMassLevel()
    {
    }

    /**
     * Test attribute "mass_factor"
     */
    public function testPropertyMassFactor()
    {
    }

    /**
     * Test attribute "price_level"
     */
    public function testPropertyPriceLevel()
    {
    }

    /**
     * Test attribute "open_date"
     */
    public function testPropertyOpenDate()
    {
    }

    /**
     * Test attribute "close_date"
     */
    public function testPropertyCloseDate()
    {
    }

    /**
     * Test attribute "restriction_percent"
     */
    public function testPropertyRestrictionPercent()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "cycle_date"
     */
    public function testPropertyCycleDate()
    {
    }

    /**
     * Test attribute "manager"
     */
    public function testPropertyManager()
    {
    }

    /**
     * Test attribute "alternate_inventory"
     */
    public function testPropertyAlternateInventory()
    {
    }

    /**
     * Test attribute "pin"
     */
    public function testPropertyPin()
    {
    }

    /**
     * Test attribute "fax_gone"
     */
    public function testPropertyFaxGone()
    {
    }

    /**
     * Test attribute "residential"
     */
    public function testPropertyResidential()
    {
    }

    /**
     * Test attribute "csr_branch"
     */
    public function testPropertyCsrBranch()
    {
    }

    /**
     * Test attribute "extrinsic_text1"
     */
    public function testPropertyExtrinsicText1()
    {
    }

    /**
     * Test attribute "extrinsic_text2"
     */
    public function testPropertyExtrinsicText2()
    {
    }

    /**
     * Test attribute "extrinsic_text3"
     */
    public function testPropertyExtrinsicText3()
    {
    }

    /**
     * Test attribute "extrinsic_number1"
     */
    public function testPropertyExtrinsicNumber1()
    {
    }

    /**
     * Test attribute "extrinsic_number2"
     */
    public function testPropertyExtrinsicNumber2()
    {
    }

    /**
     * Test attribute "extrinsic_decimal1"
     */
    public function testPropertyExtrinsicDecimal1()
    {
    }

    /**
     * Test attribute "extrinsic_decimal2"
     */
    public function testPropertyExtrinsicDecimal2()
    {
    }

    /**
     * Test attribute "modify_date"
     */
    public function testPropertyModifyDate()
    {
    }

    /**
     * Test attribute "oms_customer_id"
     */
    public function testPropertyOmsCustomerId()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }
}
