<?php
/**
 * FulfillmentProcessTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Infoplus;

/**
 * FulfillmentProcessTest Class Doc Comment
 *
 * @category    Class */
// * @description FulfillmentProcess
/**
 * @package     Infoplus
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FulfillmentProcessTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FulfillmentProcess"
     */
    public function testFulfillmentProcess()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "create_date"
     */
    public function testPropertyCreateDate()
    {
    }

    /**
     * Test attribute "modify_date"
     */
    public function testPropertyModifyDate()
    {
    }

    /**
     * Test attribute "process_no"
     */
    public function testPropertyProcessNo()
    {
    }

    /**
     * Test attribute "work_batch_id_list"
     */
    public function testPropertyWorkBatchIdList()
    {
    }

    /**
     * Test attribute "warehouse_id"
     */
    public function testPropertyWarehouseId()
    {
    }

    /**
     * Test attribute "fulfillment_plan_id"
     */
    public function testPropertyFulfillmentPlanId()
    {
    }

    /**
     * Test attribute "pick_scan_scheme_id"
     */
    public function testPropertyPickScanSchemeId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "order_smart_filter_id"
     */
    public function testPropertyOrderSmartFilterId()
    {
    }

    /**
     * Test attribute "location_smart_filter_id"
     */
    public function testPropertyLocationSmartFilterId()
    {
    }

    /**
     * Test attribute "max_orders"
     */
    public function testPropertyMaxOrders()
    {
    }

    /**
     * Test attribute "batch_max_size"
     */
    public function testPropertyBatchMaxSize()
    {
    }

    /**
     * Test attribute "batch_min_size"
     */
    public function testPropertyBatchMinSize()
    {
    }

    /**
     * Test attribute "max_cartons"
     */
    public function testPropertyMaxCartons()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "fulfillment_process_group"
     */
    public function testPropertyFulfillmentProcessGroup()
    {
    }

    /**
     * Test attribute "is_mass_distribution"
     */
    public function testPropertyIsMassDistribution()
    {
    }

    /**
     * Test attribute "priority_code"
     */
    public function testPropertyPriorityCode()
    {
    }

    /**
     * Test attribute "number_of_orders"
     */
    public function testPropertyNumberOfOrders()
    {
    }

    /**
     * Test attribute "number_of_lines"
     */
    public function testPropertyNumberOfLines()
    {
    }

    /**
     * Test attribute "number_of_sk_us"
     */
    public function testPropertyNumberOfSkUs()
    {
    }

    /**
     * Test attribute "completed_picks"
     */
    public function testPropertyCompletedPicks()
    {
    }

    /**
     * Test attribute "total_picks"
     */
    public function testPropertyTotalPicks()
    {
    }

    /**
     * Test attribute "shipped_casebreaks"
     */
    public function testPropertyShippedCasebreaks()
    {
    }

    /**
     * Test attribute "total_casebreaks_to_ship"
     */
    public function testPropertyTotalCasebreaksToShip()
    {
    }

    /**
     * Test attribute "shipped_orders"
     */
    public function testPropertyShippedOrders()
    {
    }

    /**
     * Test attribute "total_orders_to_ship"
     */
    public function testPropertyTotalOrdersToShip()
    {
    }

    /**
     * Test attribute "completed_to_do"
     */
    public function testPropertyCompletedToDo()
    {
    }

    /**
     * Test attribute "total_to_do"
     */
    public function testPropertyTotalToDo()
    {
    }

    /**
     * Test attribute "create_pick_work"
     */
    public function testPropertyCreatePickWork()
    {
    }

    /**
     * Test attribute "picking_rule"
     */
    public function testPropertyPickingRule()
    {
    }

    /**
     * Test attribute "pick_batch_group_id"
     */
    public function testPropertyPickBatchGroupId()
    {
    }

    /**
     * Test attribute "max_sk_us_per_batch"
     */
    public function testPropertyMaxSkUsPerBatch()
    {
    }

    /**
     * Test attribute "layout_rule"
     */
    public function testPropertyLayoutRule()
    {
    }

    /**
     * Test attribute "pick_sort_rule"
     */
    public function testPropertyPickSortRule()
    {
    }

    /**
     * Test attribute "location_sort"
     */
    public function testPropertyLocationSort()
    {
    }

    /**
     * Test attribute "first_pick_position"
     */
    public function testPropertyFirstPickPosition()
    {
    }

    /**
     * Test attribute "pick_list_format"
     */
    public function testPropertyPickListFormat()
    {
    }

    /**
     * Test attribute "pick_list_layout"
     */
    public function testPropertyPickListLayout()
    {
    }

    /**
     * Test attribute "pick_list_group"
     */
    public function testPropertyPickListGroup()
    {
    }

    /**
     * Test attribute "pick_list_sort"
     */
    public function testPropertyPickListSort()
    {
    }

    /**
     * Test attribute "pick_list_location_sort"
     */
    public function testPropertyPickListLocationSort()
    {
    }

    /**
     * Test attribute "pick_summary_format"
     */
    public function testPropertyPickSummaryFormat()
    {
    }

    /**
     * Test attribute "pick_summary_layout"
     */
    public function testPropertyPickSummaryLayout()
    {
    }

    /**
     * Test attribute "pick_summary_sort"
     */
    public function testPropertyPickSummarySort()
    {
    }

    /**
     * Test attribute "create_pick_summary"
     */
    public function testPropertyCreatePickSummary()
    {
    }

    /**
     * Test attribute "create_pick_list"
     */
    public function testPropertyCreatePickList()
    {
    }

    /**
     * Test attribute "pre_generate_parcel_labels"
     */
    public function testPropertyPreGenerateParcelLabels()
    {
    }

    /**
     * Test attribute "label_sort"
     */
    public function testPropertyLabelSort()
    {
    }

    /**
     * Test attribute "ship_date"
     */
    public function testPropertyShipDate()
    {
    }

    /**
     * Test attribute "auto_ship_casebreak_cartons"
     */
    public function testPropertyAutoShipCasebreakCartons()
    {
    }

    /**
     * Test attribute "auto_ship_orders"
     */
    public function testPropertyAutoShipOrders()
    {
    }

    /**
     * Test attribute "cartonize_orders"
     */
    public function testPropertyCartonizeOrders()
    {
    }

    /**
     * Test attribute "cartonization_script_id"
     */
    public function testPropertyCartonizationScriptId()
    {
    }

    /**
     * Test attribute "create_packing_slip"
     */
    public function testPropertyCreatePackingSlip()
    {
    }

    /**
     * Test attribute "override_packing_slip_template_id"
     */
    public function testPropertyOverridePackingSlipTemplateId()
    {
    }

    /**
     * Test attribute "create_order_assembly_guide"
     */
    public function testPropertyCreateOrderAssemblyGuide()
    {
    }

    /**
     * Test attribute "order_assembly_guide_layout"
     */
    public function testPropertyOrderAssemblyGuideLayout()
    {
    }

    /**
     * Test attribute "create_order_invoice"
     */
    public function testPropertyCreateOrderInvoice()
    {
    }

    /**
     * Test attribute "override_order_invoice_template_id"
     */
    public function testPropertyOverrideOrderInvoiceTemplateId()
    {
    }

    /**
     * Test attribute "create_carton_gs1128_labels"
     */
    public function testPropertyCreateCartonGs1128Labels()
    {
    }

    /**
     * Test attribute "create_line_item_each_gs1128_labels"
     */
    public function testPropertyCreateLineItemEachGs1128Labels()
    {
    }

    /**
     * Test attribute "send_to_external_shipping_system"
     */
    public function testPropertySendToExternalShippingSystem()
    {
    }

    /**
     * Test attribute "external_shipping_system_id"
     */
    public function testPropertyExternalShippingSystemId()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }
}
