<?php
/**
 * JobTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Infoplus;

/**
 * JobTest Class Doc Comment
 *
 * @category    Class */
// * @description Job
/**
 * @package     Infoplus
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class JobTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Job"
     */
    public function testJob()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "create_date"
     */
    public function testPropertyCreateDate()
    {
    }

    /**
     * Test attribute "modify_date"
     */
    public function testPropertyModifyDate()
    {
    }

    /**
     * Test attribute "source_job_recipe_id"
     */
    public function testPropertySourceJobRecipeId()
    {
    }

    /**
     * Test attribute "assembly_quantity"
     */
    public function testPropertyAssemblyQuantity()
    {
    }

    /**
     * Test attribute "warehouse_id"
     */
    public function testPropertyWarehouseId()
    {
    }

    /**
     * Test attribute "lob_id"
     */
    public function testPropertyLobId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "order_no_id"
     */
    public function testPropertyOrderNoId()
    {
    }

    /**
     * Test attribute "po_no_id"
     */
    public function testPropertyPoNoId()
    {
    }

    /**
     * Test attribute "work_batch_id"
     */
    public function testPropertyWorkBatchId()
    {
    }

    /**
     * Test attribute "layout"
     */
    public function testPropertyLayout()
    {
    }

    /**
     * Test attribute "track_assemblies"
     */
    public function testPropertyTrackAssemblies()
    {
    }

    /**
     * Test attribute "track_steps"
     */
    public function testPropertyTrackSteps()
    {
    }

    /**
     * Test attribute "job_no"
     */
    public function testPropertyJobNo()
    {
    }

    /**
     * Test attribute "assembly_instructions"
     */
    public function testPropertyAssemblyInstructions()
    {
    }

    /**
     * Test attribute "inputs"
     */
    public function testPropertyInputs()
    {
    }

    /**
     * Test attribute "outputs"
     */
    public function testPropertyOutputs()
    {
    }

    /**
     * Test attribute "steps"
     */
    public function testPropertySteps()
    {
    }

    /**
     * Test attribute "fulfillment_plan_id"
     */
    public function testPropertyFulfillmentPlanId()
    {
    }

    /**
     * Test attribute "total_picks_putbacks"
     */
    public function testPropertyTotalPicksPutbacks()
    {
    }

    /**
     * Test attribute "completed_picks_putbacks"
     */
    public function testPropertyCompletedPicksPutbacks()
    {
    }

    /**
     * Test attribute "total_assemblies"
     */
    public function testPropertyTotalAssemblies()
    {
    }

    /**
     * Test attribute "completed_assemblies"
     */
    public function testPropertyCompletedAssemblies()
    {
    }

    /**
     * Test attribute "total_steps"
     */
    public function testPropertyTotalSteps()
    {
    }

    /**
     * Test attribute "completed_steps"
     */
    public function testPropertyCompletedSteps()
    {
    }

    /**
     * Test attribute "total_receipts"
     */
    public function testPropertyTotalReceipts()
    {
    }

    /**
     * Test attribute "completed_receipts"
     */
    public function testPropertyCompletedReceipts()
    {
    }

    /**
     * Test attribute "total_to_do"
     */
    public function testPropertyTotalToDo()
    {
    }

    /**
     * Test attribute "completed_to_do"
     */
    public function testPropertyCompletedToDo()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }
}
