<?php
/**
 * AlertApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace Infoplus\Api;

use \Infoplus\Configuration;
use \Infoplus\ApiClient;
use \Infoplus\ApiException;
use \Infoplus\ObjectSerializer;

/**
 * AlertApiTest Class Doc Comment
 *
 * @category Class
 * @package  Infoplus
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AlertApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for addAlertAudit
     *
     * Add new audit for an alert
     *
     */
    public function test_addAlertAudit() {

    }
    
    /**
     * Test case for addAlertTag
     *
     * Add new tags for an alert.
     *
     */
    public function test_addAlertTag() {

    }
    
    /**
     * Test case for deleteAlertTag
     *
     * Delete a tag for an alert.
     *
     */
    public function test_deleteAlertTag() {

    }
    
    /**
     * Test case for getAlertByFilter
     *
     * Search alerts by filter
     *
     */
    public function test_getAlertByFilter() {

    }
    
    /**
     * Test case for getAlertById
     *
     * Get an alert by id
     *
     */
    public function test_getAlertById() {

    }
    
    /**
     * Test case for getAlertTags
     *
     * Get the tags for an alert.
     *
     */
    public function test_getAlertTags() {

    }
    
    /**
     * Test case for getDuplicateAlertById
     *
     * Get a duplicated an alert by id
     *
     */
    public function test_getDuplicateAlertById() {

    }
    
    /**
     * Test case for updateAlertCustomFields
     *
     * Update an alert custom fields
     *
     */
    public function test_updateAlertCustomFields() {

    }
    
}
