<?php
/**
 * ItemReceiptActivityApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace Infoplus\Api;

use \Infoplus\Configuration;
use \Infoplus\ApiClient;
use \Infoplus\ApiException;
use \Infoplus\ObjectSerializer;

/**
 * ItemReceiptActivityApiTest Class Doc Comment
 *
 * @category Class
 * @package  Infoplus
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ItemReceiptActivityApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for addItemReceiptActivity
     *
     * Create an itemReceiptActivity
     *
     */
    public function test_addItemReceiptActivity() {

    }
    
    /**
     * Test case for addItemReceiptActivityAudit
     *
     * Add new audit for an itemReceiptActivity
     *
     */
    public function test_addItemReceiptActivityAudit() {

    }
    
    /**
     * Test case for addItemReceiptActivityTag
     *
     * Add new tags for an itemReceiptActivity.
     *
     */
    public function test_addItemReceiptActivityTag() {

    }
    
    /**
     * Test case for deleteItemReceiptActivity
     *
     * Delete an itemReceiptActivity
     *
     */
    public function test_deleteItemReceiptActivity() {

    }
    
    /**
     * Test case for deleteItemReceiptActivityTag
     *
     * Delete a tag for an itemReceiptActivity.
     *
     */
    public function test_deleteItemReceiptActivityTag() {

    }
    
    /**
     * Test case for getDuplicateItemReceiptActivityById
     *
     * Get a duplicated an itemReceiptActivity by id
     *
     */
    public function test_getDuplicateItemReceiptActivityById() {

    }
    
    /**
     * Test case for getItemReceiptActivityByFilter
     *
     * Search itemReceiptActivitys by filter
     *
     */
    public function test_getItemReceiptActivityByFilter() {

    }
    
    /**
     * Test case for getItemReceiptActivityById
     *
     * Get an itemReceiptActivity by id
     *
     */
    public function test_getItemReceiptActivityById() {

    }
    
    /**
     * Test case for getItemReceiptActivityTags
     *
     * Get the tags for an itemReceiptActivity.
     *
     */
    public function test_getItemReceiptActivityTags() {

    }
    
    /**
     * Test case for updateItemReceiptActivity
     *
     * Update an itemReceiptActivity
     *
     */
    public function test_updateItemReceiptActivity() {

    }
    
}
