<?php
/**
 * ParcelInvoiceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace Infoplus\Api;

use \Infoplus\Configuration;
use \Infoplus\ApiClient;
use \Infoplus\ApiException;
use \Infoplus\ObjectSerializer;

/**
 * ParcelInvoiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Infoplus
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ParcelInvoiceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for addParcelInvoiceAudit
     *
     * Add new audit for a parcelInvoice
     *
     */
    public function test_addParcelInvoiceAudit() {

    }
    
    /**
     * Test case for addParcelInvoiceTag
     *
     * Add new tags for a parcelInvoice.
     *
     */
    public function test_addParcelInvoiceTag() {

    }
    
    /**
     * Test case for deleteParcelInvoice
     *
     * Delete a parcelInvoice
     *
     */
    public function test_deleteParcelInvoice() {

    }
    
    /**
     * Test case for deleteParcelInvoiceTag
     *
     * Delete a tag for a parcelInvoice.
     *
     */
    public function test_deleteParcelInvoiceTag() {

    }
    
    /**
     * Test case for getDuplicateParcelInvoiceById
     *
     * Get a duplicated a parcelInvoice by id
     *
     */
    public function test_getDuplicateParcelInvoiceById() {

    }
    
    /**
     * Test case for getParcelInvoiceByFilter
     *
     * Search parcelInvoices by filter
     *
     */
    public function test_getParcelInvoiceByFilter() {

    }
    
    /**
     * Test case for getParcelInvoiceById
     *
     * Get a parcelInvoice by id
     *
     */
    public function test_getParcelInvoiceById() {

    }
    
    /**
     * Test case for getParcelInvoiceTags
     *
     * Get the tags for a parcelInvoice.
     *
     */
    public function test_getParcelInvoiceTags() {

    }
    
}
