<?php
/**
 * ExternalShipmentApi
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace Infoplus\Api;

use \Infoplus\Configuration;
use \Infoplus\ApiClient;
use \Infoplus\ApiException;
use \Infoplus\ObjectSerializer;

/**
 * ExternalShipmentApi Class Doc Comment
 *
 * @category Class
 * @package  Infoplus
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ExternalShipmentApi
{

    /**
     * API Client
     * @var \Infoplus\ApiClient instance of the ApiClient
     */
    protected $apiClient;
  
    /**
     * Constructor
     * @param \Infoplus\ApiClient|null $apiClient The api client to use
     */
    function __construct($apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('https://kingsrook.localhost-testsubdomain1.infopluswms.com:8443/infoplus-wms/api');
        }
  
        $this->apiClient = $apiClient;
    }
  
    /**
     * Get API client
     * @return \Infoplus\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
  
    /**
     * Set the API client
     * @param \Infoplus\ApiClient $apiClient set the API client
     * @return ExternalShipmentApi
     */
    public function setApiClient(ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
  
    
    /**
     * addExternalShipment
     *
     * Create an externalShipment
     *
     * @param \Infoplus\Model\ExternalShipment $body ExternalShipment to be inserted. (required)
     * @return \Infoplus\Model\ExternalShipment
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function addExternalShipment($body)
    {
        list($response, $statusCode, $httpHeader) = $this->addExternalShipmentWithHttpInfo ($body);
        return $response; 
    }


    /**
     * addExternalShipmentWithHttpInfo
     *
     * Create an externalShipment
     *
     * @param \Infoplus\Model\ExternalShipment $body ExternalShipment to be inserted. (required)
     * @return Array of \Infoplus\Model\ExternalShipment, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function addExternalShipmentWithHttpInfo($body)
    {
        
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling addExternalShipment');
        }
  
        // parse inputs
        $resourcePath = "/beta/externalShipment";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams, '\Infoplus\Model\ExternalShipment'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Infoplus\ObjectSerializer::deserialize($response, '\Infoplus\Model\ExternalShipment', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Infoplus\ObjectSerializer::deserialize($e->getResponseBody(), '\Infoplus\Model\ExternalShipment', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            case 405:
                $data = \Infoplus\ObjectSerializer::deserialize($e->getResponseBody(), '\Infoplus\Model\ApiResponse', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * addExternalShipmentAudit
     *
     * Add new audit for an externalShipment
     *
     * @param int $external_shipment_id Id of the externalShipment to add an audit to (required)
     * @param string $external_shipment_audit The audit to add (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function addExternalShipmentAudit($external_shipment_id, $external_shipment_audit)
    {
        list($response, $statusCode, $httpHeader) = $this->addExternalShipmentAuditWithHttpInfo ($external_shipment_id, $external_shipment_audit);
        return $response; 
    }


    /**
     * addExternalShipmentAuditWithHttpInfo
     *
     * Add new audit for an externalShipment
     *
     * @param int $external_shipment_id Id of the externalShipment to add an audit to (required)
     * @param string $external_shipment_audit The audit to add (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function addExternalShipmentAuditWithHttpInfo($external_shipment_id, $external_shipment_audit)
    {
        
        // verify the required parameter 'external_shipment_id' is set
        if ($external_shipment_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $external_shipment_id when calling addExternalShipmentAudit');
        }
        // verify the required parameter 'external_shipment_audit' is set
        if ($external_shipment_audit === null) {
            throw new \InvalidArgumentException('Missing the required parameter $external_shipment_audit when calling addExternalShipmentAudit');
        }
  
        // parse inputs
        $resourcePath = "/beta/externalShipment/{externalShipmentId}/audit/{externalShipmentAudit}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($external_shipment_id !== null) {
            $resourcePath = str_replace(
                "{" . "externalShipmentId" . "}",
                $this->apiClient->getSerializer()->toPathValue($external_shipment_id),
                $resourcePath
            );
        }// path params
        
        if ($external_shipment_audit !== null) {
            $resourcePath = str_replace(
                "{" . "externalShipmentAudit" . "}",
                $this->apiClient->getSerializer()->toPathValue($external_shipment_audit),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'PUT',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * addExternalShipmentTag
     *
     * Add new tags for an externalShipment.
     *
     * @param int $external_shipment_id Id of the externalShipment to add a tag to (required)
     * @param string $external_shipment_tag The tag to add (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function addExternalShipmentTag($external_shipment_id, $external_shipment_tag)
    {
        list($response, $statusCode, $httpHeader) = $this->addExternalShipmentTagWithHttpInfo ($external_shipment_id, $external_shipment_tag);
        return $response; 
    }


    /**
     * addExternalShipmentTagWithHttpInfo
     *
     * Add new tags for an externalShipment.
     *
     * @param int $external_shipment_id Id of the externalShipment to add a tag to (required)
     * @param string $external_shipment_tag The tag to add (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function addExternalShipmentTagWithHttpInfo($external_shipment_id, $external_shipment_tag)
    {
        
        // verify the required parameter 'external_shipment_id' is set
        if ($external_shipment_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $external_shipment_id when calling addExternalShipmentTag');
        }
        // verify the required parameter 'external_shipment_tag' is set
        if ($external_shipment_tag === null) {
            throw new \InvalidArgumentException('Missing the required parameter $external_shipment_tag when calling addExternalShipmentTag');
        }
  
        // parse inputs
        $resourcePath = "/beta/externalShipment/{externalShipmentId}/tag/{externalShipmentTag}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($external_shipment_id !== null) {
            $resourcePath = str_replace(
                "{" . "externalShipmentId" . "}",
                $this->apiClient->getSerializer()->toPathValue($external_shipment_id),
                $resourcePath
            );
        }// path params
        
        if ($external_shipment_tag !== null) {
            $resourcePath = str_replace(
                "{" . "externalShipmentTag" . "}",
                $this->apiClient->getSerializer()->toPathValue($external_shipment_tag),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'PUT',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * deleteExternalShipment
     *
     * Delete an externalShipment
     *
     * @param int $external_shipment_id Id of the externalShipment to be deleted. (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function deleteExternalShipment($external_shipment_id)
    {
        list($response, $statusCode, $httpHeader) = $this->deleteExternalShipmentWithHttpInfo ($external_shipment_id);
        return $response; 
    }


    /**
     * deleteExternalShipmentWithHttpInfo
     *
     * Delete an externalShipment
     *
     * @param int $external_shipment_id Id of the externalShipment to be deleted. (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function deleteExternalShipmentWithHttpInfo($external_shipment_id)
    {
        
        // verify the required parameter 'external_shipment_id' is set
        if ($external_shipment_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $external_shipment_id when calling deleteExternalShipment');
        }
  
        // parse inputs
        $resourcePath = "/beta/externalShipment/{externalShipmentId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($external_shipment_id !== null) {
            $resourcePath = str_replace(
                "{" . "externalShipmentId" . "}",
                $this->apiClient->getSerializer()->toPathValue($external_shipment_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'DELETE',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * deleteExternalShipmentTag
     *
     * Delete a tag for an externalShipment.
     *
     * @param int $external_shipment_id Id of the externalShipment to remove tag from (required)
     * @param string $external_shipment_tag The tag to delete (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function deleteExternalShipmentTag($external_shipment_id, $external_shipment_tag)
    {
        list($response, $statusCode, $httpHeader) = $this->deleteExternalShipmentTagWithHttpInfo ($external_shipment_id, $external_shipment_tag);
        return $response; 
    }


    /**
     * deleteExternalShipmentTagWithHttpInfo
     *
     * Delete a tag for an externalShipment.
     *
     * @param int $external_shipment_id Id of the externalShipment to remove tag from (required)
     * @param string $external_shipment_tag The tag to delete (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function deleteExternalShipmentTagWithHttpInfo($external_shipment_id, $external_shipment_tag)
    {
        
        // verify the required parameter 'external_shipment_id' is set
        if ($external_shipment_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $external_shipment_id when calling deleteExternalShipmentTag');
        }
        // verify the required parameter 'external_shipment_tag' is set
        if ($external_shipment_tag === null) {
            throw new \InvalidArgumentException('Missing the required parameter $external_shipment_tag when calling deleteExternalShipmentTag');
        }
  
        // parse inputs
        $resourcePath = "/beta/externalShipment/{externalShipmentId}/tag/{externalShipmentTag}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($external_shipment_id !== null) {
            $resourcePath = str_replace(
                "{" . "externalShipmentId" . "}",
                $this->apiClient->getSerializer()->toPathValue($external_shipment_id),
                $resourcePath
            );
        }// path params
        
        if ($external_shipment_tag !== null) {
            $resourcePath = str_replace(
                "{" . "externalShipmentTag" . "}",
                $this->apiClient->getSerializer()->toPathValue($external_shipment_tag),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'DELETE',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * getDuplicateExternalShipmentById
     *
     * Get a duplicated an externalShipment by id
     *
     * @param int $external_shipment_id Id of the externalShipment to be duplicated. (required)
     * @return \Infoplus\Model\ExternalShipment
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getDuplicateExternalShipmentById($external_shipment_id)
    {
        list($response, $statusCode, $httpHeader) = $this->getDuplicateExternalShipmentByIdWithHttpInfo ($external_shipment_id);
        return $response; 
    }


    /**
     * getDuplicateExternalShipmentByIdWithHttpInfo
     *
     * Get a duplicated an externalShipment by id
     *
     * @param int $external_shipment_id Id of the externalShipment to be duplicated. (required)
     * @return Array of \Infoplus\Model\ExternalShipment, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getDuplicateExternalShipmentByIdWithHttpInfo($external_shipment_id)
    {
        
        // verify the required parameter 'external_shipment_id' is set
        if ($external_shipment_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $external_shipment_id when calling getDuplicateExternalShipmentById');
        }
  
        // parse inputs
        $resourcePath = "/beta/externalShipment/duplicate/{externalShipmentId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($external_shipment_id !== null) {
            $resourcePath = str_replace(
                "{" . "externalShipmentId" . "}",
                $this->apiClient->getSerializer()->toPathValue($external_shipment_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams, '\Infoplus\Model\ExternalShipment'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Infoplus\ObjectSerializer::deserialize($response, '\Infoplus\Model\ExternalShipment', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Infoplus\ObjectSerializer::deserialize($e->getResponseBody(), '\Infoplus\Model\ExternalShipment', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getExternalShipmentByFilter
     *
     * Search externalShipments by filter
     *
     * @param string $filter Query string, used to filter results. (optional)
     * @param int $page Result page number.  Defaults to 1. (optional)
     * @param int $limit Maximum results per page.  Defaults to 20.  Max allowed value is 250. (optional)
     * @param string $sort Sort results by specified field. (optional)
     * @return \Infoplus\Model\ExternalShipment[]
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getExternalShipmentByFilter($filter = null, $page = null, $limit = null, $sort = null)
    {
        list($response, $statusCode, $httpHeader) = $this->getExternalShipmentByFilterWithHttpInfo ($filter, $page, $limit, $sort);
        return $response; 
    }


    /**
     * getExternalShipmentByFilterWithHttpInfo
     *
     * Search externalShipments by filter
     *
     * @param string $filter Query string, used to filter results. (optional)
     * @param int $page Result page number.  Defaults to 1. (optional)
     * @param int $limit Maximum results per page.  Defaults to 20.  Max allowed value is 250. (optional)
     * @param string $sort Sort results by specified field. (optional)
     * @return Array of \Infoplus\Model\ExternalShipment[], HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getExternalShipmentByFilterWithHttpInfo($filter = null, $page = null, $limit = null, $sort = null)
    {
        
  
        // parse inputs
        $resourcePath = "/beta/externalShipment/search";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        // query params
        
        if ($filter !== null) {
            $queryParams['filter'] = $this->apiClient->getSerializer()->toQueryValue($filter);
        }// query params
        
        if ($page !== null) {
            $queryParams['page'] = $this->apiClient->getSerializer()->toQueryValue($page);
        }// query params
        
        if ($limit !== null) {
            $queryParams['limit'] = $this->apiClient->getSerializer()->toQueryValue($limit);
        }// query params
        
        if ($sort !== null) {
            $queryParams['sort'] = $this->apiClient->getSerializer()->toQueryValue($sort);
        }
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams, '\Infoplus\Model\ExternalShipment[]'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Infoplus\ObjectSerializer::deserialize($response, '\Infoplus\Model\ExternalShipment[]', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Infoplus\ObjectSerializer::deserialize($e->getResponseBody(), '\Infoplus\Model\ExternalShipment[]', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getExternalShipmentById
     *
     * Get an externalShipment by id
     *
     * @param int $external_shipment_id Id of the externalShipment to be returned. (required)
     * @return \Infoplus\Model\ExternalShipment
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getExternalShipmentById($external_shipment_id)
    {
        list($response, $statusCode, $httpHeader) = $this->getExternalShipmentByIdWithHttpInfo ($external_shipment_id);
        return $response; 
    }


    /**
     * getExternalShipmentByIdWithHttpInfo
     *
     * Get an externalShipment by id
     *
     * @param int $external_shipment_id Id of the externalShipment to be returned. (required)
     * @return Array of \Infoplus\Model\ExternalShipment, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getExternalShipmentByIdWithHttpInfo($external_shipment_id)
    {
        
        // verify the required parameter 'external_shipment_id' is set
        if ($external_shipment_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $external_shipment_id when calling getExternalShipmentById');
        }
  
        // parse inputs
        $resourcePath = "/beta/externalShipment/{externalShipmentId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($external_shipment_id !== null) {
            $resourcePath = str_replace(
                "{" . "externalShipmentId" . "}",
                $this->apiClient->getSerializer()->toPathValue($external_shipment_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams, '\Infoplus\Model\ExternalShipment'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Infoplus\ObjectSerializer::deserialize($response, '\Infoplus\Model\ExternalShipment', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Infoplus\ObjectSerializer::deserialize($e->getResponseBody(), '\Infoplus\Model\ExternalShipment', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getExternalShipmentTags
     *
     * Get the tags for an externalShipment.
     *
     * @param int $external_shipment_id Id of the externalShipment to get tags for (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getExternalShipmentTags($external_shipment_id)
    {
        list($response, $statusCode, $httpHeader) = $this->getExternalShipmentTagsWithHttpInfo ($external_shipment_id);
        return $response; 
    }


    /**
     * getExternalShipmentTagsWithHttpInfo
     *
     * Get the tags for an externalShipment.
     *
     * @param int $external_shipment_id Id of the externalShipment to get tags for (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getExternalShipmentTagsWithHttpInfo($external_shipment_id)
    {
        
        // verify the required parameter 'external_shipment_id' is set
        if ($external_shipment_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $external_shipment_id when calling getExternalShipmentTags');
        }
  
        // parse inputs
        $resourcePath = "/beta/externalShipment/{externalShipmentId}/tag";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($external_shipment_id !== null) {
            $resourcePath = str_replace(
                "{" . "externalShipmentId" . "}",
                $this->apiClient->getSerializer()->toPathValue($external_shipment_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * updateExternalShipment
     *
     * Update an externalShipment
     *
     * @param \Infoplus\Model\ExternalShipment $body ExternalShipment to be updated. (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function updateExternalShipment($body)
    {
        list($response, $statusCode, $httpHeader) = $this->updateExternalShipmentWithHttpInfo ($body);
        return $response; 
    }


    /**
     * updateExternalShipmentWithHttpInfo
     *
     * Update an externalShipment
     *
     * @param \Infoplus\Model\ExternalShipment $body ExternalShipment to be updated. (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function updateExternalShipmentWithHttpInfo($body)
    {
        
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling updateExternalShipment');
        }
  
        // parse inputs
        $resourcePath = "/beta/externalShipment";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'PUT',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * updateExternalShipmentCustomFields
     *
     * Update an externalShipment custom fields
     *
     * @param \Infoplus\Model\ExternalShipment $body ExternalShipment to be updated. (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function updateExternalShipmentCustomFields($body)
    {
        list($response, $statusCode, $httpHeader) = $this->updateExternalShipmentCustomFieldsWithHttpInfo ($body);
        return $response; 
    }


    /**
     * updateExternalShipmentCustomFieldsWithHttpInfo
     *
     * Update an externalShipment custom fields
     *
     * @param \Infoplus\Model\ExternalShipment $body ExternalShipment to be updated. (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function updateExternalShipmentCustomFieldsWithHttpInfo($body)
    {
        
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling updateExternalShipmentCustomFields');
        }
  
        // parse inputs
        $resourcePath = "/beta/externalShipment/customFields";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'PUT',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
}
