<?php
/**
 * ItemLowstockCodeApi
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace Infoplus\Api;

use \Infoplus\Configuration;
use \Infoplus\ApiClient;
use \Infoplus\ApiException;
use \Infoplus\ObjectSerializer;

/**
 * ItemLowstockCodeApi Class Doc Comment
 *
 * @category Class
 * @package  Infoplus
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ItemLowstockCodeApi
{

    /**
     * API Client
     * @var \Infoplus\ApiClient instance of the ApiClient
     */
    protected $apiClient;
  
    /**
     * Constructor
     * @param \Infoplus\ApiClient|null $apiClient The api client to use
     */
    function __construct($apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('https://kingsrook.localhost-testsubdomain1.infopluswms.com:8443/infoplus-wms/api');
        }
  
        $this->apiClient = $apiClient;
    }
  
    /**
     * Get API client
     * @return \Infoplus\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
  
    /**
     * Set the API client
     * @param \Infoplus\ApiClient $apiClient set the API client
     * @return ItemLowstockCodeApi
     */
    public function setApiClient(ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
  
    
    /**
     * addItemLowstockCode
     *
     * Create an itemLowstockCode
     *
     * @param \Infoplus\Model\ItemLowstockCode $body ItemLowstockCode to be inserted. (required)
     * @return \Infoplus\Model\ItemLowstockCode
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function addItemLowstockCode($body)
    {
        list($response, $statusCode, $httpHeader) = $this->addItemLowstockCodeWithHttpInfo ($body);
        return $response; 
    }


    /**
     * addItemLowstockCodeWithHttpInfo
     *
     * Create an itemLowstockCode
     *
     * @param \Infoplus\Model\ItemLowstockCode $body ItemLowstockCode to be inserted. (required)
     * @return Array of \Infoplus\Model\ItemLowstockCode, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function addItemLowstockCodeWithHttpInfo($body)
    {
        
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling addItemLowstockCode');
        }
  
        // parse inputs
        $resourcePath = "/beta/itemLowstockCode";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams, '\Infoplus\Model\ItemLowstockCode'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Infoplus\ObjectSerializer::deserialize($response, '\Infoplus\Model\ItemLowstockCode', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Infoplus\ObjectSerializer::deserialize($e->getResponseBody(), '\Infoplus\Model\ItemLowstockCode', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            case 405:
                $data = \Infoplus\ObjectSerializer::deserialize($e->getResponseBody(), '\Infoplus\Model\ApiResponse', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * addItemLowstockCodeAudit
     *
     * Add new audit for an itemLowstockCode
     *
     * @param int $item_lowstock_code_id Id of the itemLowstockCode to add an audit to (required)
     * @param string $item_lowstock_code_audit The audit to add (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function addItemLowstockCodeAudit($item_lowstock_code_id, $item_lowstock_code_audit)
    {
        list($response, $statusCode, $httpHeader) = $this->addItemLowstockCodeAuditWithHttpInfo ($item_lowstock_code_id, $item_lowstock_code_audit);
        return $response; 
    }


    /**
     * addItemLowstockCodeAuditWithHttpInfo
     *
     * Add new audit for an itemLowstockCode
     *
     * @param int $item_lowstock_code_id Id of the itemLowstockCode to add an audit to (required)
     * @param string $item_lowstock_code_audit The audit to add (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function addItemLowstockCodeAuditWithHttpInfo($item_lowstock_code_id, $item_lowstock_code_audit)
    {
        
        // verify the required parameter 'item_lowstock_code_id' is set
        if ($item_lowstock_code_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $item_lowstock_code_id when calling addItemLowstockCodeAudit');
        }
        // verify the required parameter 'item_lowstock_code_audit' is set
        if ($item_lowstock_code_audit === null) {
            throw new \InvalidArgumentException('Missing the required parameter $item_lowstock_code_audit when calling addItemLowstockCodeAudit');
        }
  
        // parse inputs
        $resourcePath = "/beta/itemLowstockCode/{itemLowstockCodeId}/audit/{itemLowstockCodeAudit}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($item_lowstock_code_id !== null) {
            $resourcePath = str_replace(
                "{" . "itemLowstockCodeId" . "}",
                $this->apiClient->getSerializer()->toPathValue($item_lowstock_code_id),
                $resourcePath
            );
        }// path params
        
        if ($item_lowstock_code_audit !== null) {
            $resourcePath = str_replace(
                "{" . "itemLowstockCodeAudit" . "}",
                $this->apiClient->getSerializer()->toPathValue($item_lowstock_code_audit),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'PUT',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * addItemLowstockCodeTag
     *
     * Add new tags for an itemLowstockCode.
     *
     * @param int $item_lowstock_code_id Id of the itemLowstockCode to add a tag to (required)
     * @param string $item_lowstock_code_tag The tag to add (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function addItemLowstockCodeTag($item_lowstock_code_id, $item_lowstock_code_tag)
    {
        list($response, $statusCode, $httpHeader) = $this->addItemLowstockCodeTagWithHttpInfo ($item_lowstock_code_id, $item_lowstock_code_tag);
        return $response; 
    }


    /**
     * addItemLowstockCodeTagWithHttpInfo
     *
     * Add new tags for an itemLowstockCode.
     *
     * @param int $item_lowstock_code_id Id of the itemLowstockCode to add a tag to (required)
     * @param string $item_lowstock_code_tag The tag to add (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function addItemLowstockCodeTagWithHttpInfo($item_lowstock_code_id, $item_lowstock_code_tag)
    {
        
        // verify the required parameter 'item_lowstock_code_id' is set
        if ($item_lowstock_code_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $item_lowstock_code_id when calling addItemLowstockCodeTag');
        }
        // verify the required parameter 'item_lowstock_code_tag' is set
        if ($item_lowstock_code_tag === null) {
            throw new \InvalidArgumentException('Missing the required parameter $item_lowstock_code_tag when calling addItemLowstockCodeTag');
        }
  
        // parse inputs
        $resourcePath = "/beta/itemLowstockCode/{itemLowstockCodeId}/tag/{itemLowstockCodeTag}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($item_lowstock_code_id !== null) {
            $resourcePath = str_replace(
                "{" . "itemLowstockCodeId" . "}",
                $this->apiClient->getSerializer()->toPathValue($item_lowstock_code_id),
                $resourcePath
            );
        }// path params
        
        if ($item_lowstock_code_tag !== null) {
            $resourcePath = str_replace(
                "{" . "itemLowstockCodeTag" . "}",
                $this->apiClient->getSerializer()->toPathValue($item_lowstock_code_tag),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'PUT',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * deleteItemLowstockCode
     *
     * Delete an itemLowstockCode
     *
     * @param int $item_lowstock_code_id Id of the itemLowstockCode to be deleted. (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function deleteItemLowstockCode($item_lowstock_code_id)
    {
        list($response, $statusCode, $httpHeader) = $this->deleteItemLowstockCodeWithHttpInfo ($item_lowstock_code_id);
        return $response; 
    }


    /**
     * deleteItemLowstockCodeWithHttpInfo
     *
     * Delete an itemLowstockCode
     *
     * @param int $item_lowstock_code_id Id of the itemLowstockCode to be deleted. (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function deleteItemLowstockCodeWithHttpInfo($item_lowstock_code_id)
    {
        
        // verify the required parameter 'item_lowstock_code_id' is set
        if ($item_lowstock_code_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $item_lowstock_code_id when calling deleteItemLowstockCode');
        }
  
        // parse inputs
        $resourcePath = "/beta/itemLowstockCode/{itemLowstockCodeId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($item_lowstock_code_id !== null) {
            $resourcePath = str_replace(
                "{" . "itemLowstockCodeId" . "}",
                $this->apiClient->getSerializer()->toPathValue($item_lowstock_code_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'DELETE',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * deleteItemLowstockCodeTag
     *
     * Delete a tag for an itemLowstockCode.
     *
     * @param int $item_lowstock_code_id Id of the itemLowstockCode to remove tag from (required)
     * @param string $item_lowstock_code_tag The tag to delete (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function deleteItemLowstockCodeTag($item_lowstock_code_id, $item_lowstock_code_tag)
    {
        list($response, $statusCode, $httpHeader) = $this->deleteItemLowstockCodeTagWithHttpInfo ($item_lowstock_code_id, $item_lowstock_code_tag);
        return $response; 
    }


    /**
     * deleteItemLowstockCodeTagWithHttpInfo
     *
     * Delete a tag for an itemLowstockCode.
     *
     * @param int $item_lowstock_code_id Id of the itemLowstockCode to remove tag from (required)
     * @param string $item_lowstock_code_tag The tag to delete (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function deleteItemLowstockCodeTagWithHttpInfo($item_lowstock_code_id, $item_lowstock_code_tag)
    {
        
        // verify the required parameter 'item_lowstock_code_id' is set
        if ($item_lowstock_code_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $item_lowstock_code_id when calling deleteItemLowstockCodeTag');
        }
        // verify the required parameter 'item_lowstock_code_tag' is set
        if ($item_lowstock_code_tag === null) {
            throw new \InvalidArgumentException('Missing the required parameter $item_lowstock_code_tag when calling deleteItemLowstockCodeTag');
        }
  
        // parse inputs
        $resourcePath = "/beta/itemLowstockCode/{itemLowstockCodeId}/tag/{itemLowstockCodeTag}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($item_lowstock_code_id !== null) {
            $resourcePath = str_replace(
                "{" . "itemLowstockCodeId" . "}",
                $this->apiClient->getSerializer()->toPathValue($item_lowstock_code_id),
                $resourcePath
            );
        }// path params
        
        if ($item_lowstock_code_tag !== null) {
            $resourcePath = str_replace(
                "{" . "itemLowstockCodeTag" . "}",
                $this->apiClient->getSerializer()->toPathValue($item_lowstock_code_tag),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'DELETE',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * getDuplicateItemLowstockCodeById
     *
     * Get a duplicated an itemLowstockCode by id
     *
     * @param int $item_lowstock_code_id Id of the itemLowstockCode to be duplicated. (required)
     * @return \Infoplus\Model\ItemLowstockCode
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getDuplicateItemLowstockCodeById($item_lowstock_code_id)
    {
        list($response, $statusCode, $httpHeader) = $this->getDuplicateItemLowstockCodeByIdWithHttpInfo ($item_lowstock_code_id);
        return $response; 
    }


    /**
     * getDuplicateItemLowstockCodeByIdWithHttpInfo
     *
     * Get a duplicated an itemLowstockCode by id
     *
     * @param int $item_lowstock_code_id Id of the itemLowstockCode to be duplicated. (required)
     * @return Array of \Infoplus\Model\ItemLowstockCode, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getDuplicateItemLowstockCodeByIdWithHttpInfo($item_lowstock_code_id)
    {
        
        // verify the required parameter 'item_lowstock_code_id' is set
        if ($item_lowstock_code_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $item_lowstock_code_id when calling getDuplicateItemLowstockCodeById');
        }
  
        // parse inputs
        $resourcePath = "/beta/itemLowstockCode/duplicate/{itemLowstockCodeId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($item_lowstock_code_id !== null) {
            $resourcePath = str_replace(
                "{" . "itemLowstockCodeId" . "}",
                $this->apiClient->getSerializer()->toPathValue($item_lowstock_code_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams, '\Infoplus\Model\ItemLowstockCode'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Infoplus\ObjectSerializer::deserialize($response, '\Infoplus\Model\ItemLowstockCode', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Infoplus\ObjectSerializer::deserialize($e->getResponseBody(), '\Infoplus\Model\ItemLowstockCode', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getItemLowstockCodeByFilter
     *
     * Search itemLowstockCodes by filter
     *
     * @param string $filter Query string, used to filter results. (optional)
     * @param int $page Result page number.  Defaults to 1. (optional)
     * @param int $limit Maximum results per page.  Defaults to 20.  Max allowed value is 250. (optional)
     * @param string $sort Sort results by specified field. (optional)
     * @return \Infoplus\Model\ItemLowstockCode[]
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getItemLowstockCodeByFilter($filter = null, $page = null, $limit = null, $sort = null)
    {
        list($response, $statusCode, $httpHeader) = $this->getItemLowstockCodeByFilterWithHttpInfo ($filter, $page, $limit, $sort);
        return $response; 
    }


    /**
     * getItemLowstockCodeByFilterWithHttpInfo
     *
     * Search itemLowstockCodes by filter
     *
     * @param string $filter Query string, used to filter results. (optional)
     * @param int $page Result page number.  Defaults to 1. (optional)
     * @param int $limit Maximum results per page.  Defaults to 20.  Max allowed value is 250. (optional)
     * @param string $sort Sort results by specified field. (optional)
     * @return Array of \Infoplus\Model\ItemLowstockCode[], HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getItemLowstockCodeByFilterWithHttpInfo($filter = null, $page = null, $limit = null, $sort = null)
    {
        
  
        // parse inputs
        $resourcePath = "/beta/itemLowstockCode/search";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        // query params
        
        if ($filter !== null) {
            $queryParams['filter'] = $this->apiClient->getSerializer()->toQueryValue($filter);
        }// query params
        
        if ($page !== null) {
            $queryParams['page'] = $this->apiClient->getSerializer()->toQueryValue($page);
        }// query params
        
        if ($limit !== null) {
            $queryParams['limit'] = $this->apiClient->getSerializer()->toQueryValue($limit);
        }// query params
        
        if ($sort !== null) {
            $queryParams['sort'] = $this->apiClient->getSerializer()->toQueryValue($sort);
        }
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams, '\Infoplus\Model\ItemLowstockCode[]'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Infoplus\ObjectSerializer::deserialize($response, '\Infoplus\Model\ItemLowstockCode[]', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Infoplus\ObjectSerializer::deserialize($e->getResponseBody(), '\Infoplus\Model\ItemLowstockCode[]', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getItemLowstockCodeById
     *
     * Get an itemLowstockCode by id
     *
     * @param int $item_lowstock_code_id Id of the itemLowstockCode to be returned. (required)
     * @return \Infoplus\Model\ItemLowstockCode
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getItemLowstockCodeById($item_lowstock_code_id)
    {
        list($response, $statusCode, $httpHeader) = $this->getItemLowstockCodeByIdWithHttpInfo ($item_lowstock_code_id);
        return $response; 
    }


    /**
     * getItemLowstockCodeByIdWithHttpInfo
     *
     * Get an itemLowstockCode by id
     *
     * @param int $item_lowstock_code_id Id of the itemLowstockCode to be returned. (required)
     * @return Array of \Infoplus\Model\ItemLowstockCode, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getItemLowstockCodeByIdWithHttpInfo($item_lowstock_code_id)
    {
        
        // verify the required parameter 'item_lowstock_code_id' is set
        if ($item_lowstock_code_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $item_lowstock_code_id when calling getItemLowstockCodeById');
        }
  
        // parse inputs
        $resourcePath = "/beta/itemLowstockCode/{itemLowstockCodeId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($item_lowstock_code_id !== null) {
            $resourcePath = str_replace(
                "{" . "itemLowstockCodeId" . "}",
                $this->apiClient->getSerializer()->toPathValue($item_lowstock_code_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams, '\Infoplus\Model\ItemLowstockCode'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Infoplus\ObjectSerializer::deserialize($response, '\Infoplus\Model\ItemLowstockCode', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Infoplus\ObjectSerializer::deserialize($e->getResponseBody(), '\Infoplus\Model\ItemLowstockCode', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getItemLowstockCodeTags
     *
     * Get the tags for an itemLowstockCode.
     *
     * @param int $item_lowstock_code_id Id of the itemLowstockCode to get tags for (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getItemLowstockCodeTags($item_lowstock_code_id)
    {
        list($response, $statusCode, $httpHeader) = $this->getItemLowstockCodeTagsWithHttpInfo ($item_lowstock_code_id);
        return $response; 
    }


    /**
     * getItemLowstockCodeTagsWithHttpInfo
     *
     * Get the tags for an itemLowstockCode.
     *
     * @param int $item_lowstock_code_id Id of the itemLowstockCode to get tags for (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getItemLowstockCodeTagsWithHttpInfo($item_lowstock_code_id)
    {
        
        // verify the required parameter 'item_lowstock_code_id' is set
        if ($item_lowstock_code_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $item_lowstock_code_id when calling getItemLowstockCodeTags');
        }
  
        // parse inputs
        $resourcePath = "/beta/itemLowstockCode/{itemLowstockCodeId}/tag";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($item_lowstock_code_id !== null) {
            $resourcePath = str_replace(
                "{" . "itemLowstockCodeId" . "}",
                $this->apiClient->getSerializer()->toPathValue($item_lowstock_code_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * updateItemLowstockCode
     *
     * Update an itemLowstockCode
     *
     * @param \Infoplus\Model\ItemLowstockCode $body ItemLowstockCode to be updated. (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function updateItemLowstockCode($body)
    {
        list($response, $statusCode, $httpHeader) = $this->updateItemLowstockCodeWithHttpInfo ($body);
        return $response; 
    }


    /**
     * updateItemLowstockCodeWithHttpInfo
     *
     * Update an itemLowstockCode
     *
     * @param \Infoplus\Model\ItemLowstockCode $body ItemLowstockCode to be updated. (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function updateItemLowstockCodeWithHttpInfo($body)
    {
        
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling updateItemLowstockCode');
        }
  
        // parse inputs
        $resourcePath = "/beta/itemLowstockCode";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'PUT',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
}
