<?php
/**
 * VendorApi
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace Infoplus\Api;

use \Infoplus\Configuration;
use \Infoplus\ApiClient;
use \Infoplus\ApiException;
use \Infoplus\ObjectSerializer;

/**
 * VendorApi Class Doc Comment
 *
 * @category Class
 * @package  Infoplus
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VendorApi
{

    /**
     * API Client
     * @var \Infoplus\ApiClient instance of the ApiClient
     */
    protected $apiClient;
  
    /**
     * Constructor
     * @param \Infoplus\ApiClient|null $apiClient The api client to use
     */
    function __construct($apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('https://kingsrook.localhost-testsubdomain1.infopluswms.com:8443/infoplus-wms/api');
        }
  
        $this->apiClient = $apiClient;
    }
  
    /**
     * Get API client
     * @return \Infoplus\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
  
    /**
     * Set the API client
     * @param \Infoplus\ApiClient $apiClient set the API client
     * @return VendorApi
     */
    public function setApiClient(ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
  
    
    /**
     * addVendor
     *
     * Create a vendor
     *
     * @param \Infoplus\Model\Vendor $body Vendor to be inserted. (required)
     * @return \Infoplus\Model\Vendor
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function addVendor($body)
    {
        list($response, $statusCode, $httpHeader) = $this->addVendorWithHttpInfo ($body);
        return $response; 
    }


    /**
     * addVendorWithHttpInfo
     *
     * Create a vendor
     *
     * @param \Infoplus\Model\Vendor $body Vendor to be inserted. (required)
     * @return Array of \Infoplus\Model\Vendor, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function addVendorWithHttpInfo($body)
    {
        
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling addVendor');
        }
  
        // parse inputs
        $resourcePath = "/beta/vendor";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams, '\Infoplus\Model\Vendor'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Infoplus\ObjectSerializer::deserialize($response, '\Infoplus\Model\Vendor', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Infoplus\ObjectSerializer::deserialize($e->getResponseBody(), '\Infoplus\Model\Vendor', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            case 405:
                $data = \Infoplus\ObjectSerializer::deserialize($e->getResponseBody(), '\Infoplus\Model\ApiResponse', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * addVendorAudit
     *
     * Add new audit for a vendor
     *
     * @param int $vendor_id Id of the vendor to add an audit to (required)
     * @param string $vendor_audit The audit to add (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function addVendorAudit($vendor_id, $vendor_audit)
    {
        list($response, $statusCode, $httpHeader) = $this->addVendorAuditWithHttpInfo ($vendor_id, $vendor_audit);
        return $response; 
    }


    /**
     * addVendorAuditWithHttpInfo
     *
     * Add new audit for a vendor
     *
     * @param int $vendor_id Id of the vendor to add an audit to (required)
     * @param string $vendor_audit The audit to add (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function addVendorAuditWithHttpInfo($vendor_id, $vendor_audit)
    {
        
        // verify the required parameter 'vendor_id' is set
        if ($vendor_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $vendor_id when calling addVendorAudit');
        }
        // verify the required parameter 'vendor_audit' is set
        if ($vendor_audit === null) {
            throw new \InvalidArgumentException('Missing the required parameter $vendor_audit when calling addVendorAudit');
        }
  
        // parse inputs
        $resourcePath = "/beta/vendor/{vendorId}/audit/{vendorAudit}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($vendor_id !== null) {
            $resourcePath = str_replace(
                "{" . "vendorId" . "}",
                $this->apiClient->getSerializer()->toPathValue($vendor_id),
                $resourcePath
            );
        }// path params
        
        if ($vendor_audit !== null) {
            $resourcePath = str_replace(
                "{" . "vendorAudit" . "}",
                $this->apiClient->getSerializer()->toPathValue($vendor_audit),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'PUT',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * addVendorTag
     *
     * Add new tags for a vendor.
     *
     * @param int $vendor_id Id of the vendor to add a tag to (required)
     * @param string $vendor_tag The tag to add (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function addVendorTag($vendor_id, $vendor_tag)
    {
        list($response, $statusCode, $httpHeader) = $this->addVendorTagWithHttpInfo ($vendor_id, $vendor_tag);
        return $response; 
    }


    /**
     * addVendorTagWithHttpInfo
     *
     * Add new tags for a vendor.
     *
     * @param int $vendor_id Id of the vendor to add a tag to (required)
     * @param string $vendor_tag The tag to add (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function addVendorTagWithHttpInfo($vendor_id, $vendor_tag)
    {
        
        // verify the required parameter 'vendor_id' is set
        if ($vendor_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $vendor_id when calling addVendorTag');
        }
        // verify the required parameter 'vendor_tag' is set
        if ($vendor_tag === null) {
            throw new \InvalidArgumentException('Missing the required parameter $vendor_tag when calling addVendorTag');
        }
  
        // parse inputs
        $resourcePath = "/beta/vendor/{vendorId}/tag/{vendorTag}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($vendor_id !== null) {
            $resourcePath = str_replace(
                "{" . "vendorId" . "}",
                $this->apiClient->getSerializer()->toPathValue($vendor_id),
                $resourcePath
            );
        }// path params
        
        if ($vendor_tag !== null) {
            $resourcePath = str_replace(
                "{" . "vendorTag" . "}",
                $this->apiClient->getSerializer()->toPathValue($vendor_tag),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'PUT',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * deleteVendor
     *
     * Delete a vendor
     *
     * @param int $vendor_id Id of the vendor to be deleted. (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function deleteVendor($vendor_id)
    {
        list($response, $statusCode, $httpHeader) = $this->deleteVendorWithHttpInfo ($vendor_id);
        return $response; 
    }


    /**
     * deleteVendorWithHttpInfo
     *
     * Delete a vendor
     *
     * @param int $vendor_id Id of the vendor to be deleted. (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function deleteVendorWithHttpInfo($vendor_id)
    {
        
        // verify the required parameter 'vendor_id' is set
        if ($vendor_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $vendor_id when calling deleteVendor');
        }
  
        // parse inputs
        $resourcePath = "/beta/vendor/{vendorId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($vendor_id !== null) {
            $resourcePath = str_replace(
                "{" . "vendorId" . "}",
                $this->apiClient->getSerializer()->toPathValue($vendor_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'DELETE',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * deleteVendorTag
     *
     * Delete a tag for a vendor.
     *
     * @param int $vendor_id Id of the vendor to remove tag from (required)
     * @param string $vendor_tag The tag to delete (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function deleteVendorTag($vendor_id, $vendor_tag)
    {
        list($response, $statusCode, $httpHeader) = $this->deleteVendorTagWithHttpInfo ($vendor_id, $vendor_tag);
        return $response; 
    }


    /**
     * deleteVendorTagWithHttpInfo
     *
     * Delete a tag for a vendor.
     *
     * @param int $vendor_id Id of the vendor to remove tag from (required)
     * @param string $vendor_tag The tag to delete (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function deleteVendorTagWithHttpInfo($vendor_id, $vendor_tag)
    {
        
        // verify the required parameter 'vendor_id' is set
        if ($vendor_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $vendor_id when calling deleteVendorTag');
        }
        // verify the required parameter 'vendor_tag' is set
        if ($vendor_tag === null) {
            throw new \InvalidArgumentException('Missing the required parameter $vendor_tag when calling deleteVendorTag');
        }
  
        // parse inputs
        $resourcePath = "/beta/vendor/{vendorId}/tag/{vendorTag}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($vendor_id !== null) {
            $resourcePath = str_replace(
                "{" . "vendorId" . "}",
                $this->apiClient->getSerializer()->toPathValue($vendor_id),
                $resourcePath
            );
        }// path params
        
        if ($vendor_tag !== null) {
            $resourcePath = str_replace(
                "{" . "vendorTag" . "}",
                $this->apiClient->getSerializer()->toPathValue($vendor_tag),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'DELETE',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * getDuplicateVendorById
     *
     * Get a duplicated a vendor by id
     *
     * @param int $vendor_id Id of the vendor to be duplicated. (required)
     * @return \Infoplus\Model\Vendor
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getDuplicateVendorById($vendor_id)
    {
        list($response, $statusCode, $httpHeader) = $this->getDuplicateVendorByIdWithHttpInfo ($vendor_id);
        return $response; 
    }


    /**
     * getDuplicateVendorByIdWithHttpInfo
     *
     * Get a duplicated a vendor by id
     *
     * @param int $vendor_id Id of the vendor to be duplicated. (required)
     * @return Array of \Infoplus\Model\Vendor, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getDuplicateVendorByIdWithHttpInfo($vendor_id)
    {
        
        // verify the required parameter 'vendor_id' is set
        if ($vendor_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $vendor_id when calling getDuplicateVendorById');
        }
  
        // parse inputs
        $resourcePath = "/beta/vendor/duplicate/{vendorId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($vendor_id !== null) {
            $resourcePath = str_replace(
                "{" . "vendorId" . "}",
                $this->apiClient->getSerializer()->toPathValue($vendor_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams, '\Infoplus\Model\Vendor'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Infoplus\ObjectSerializer::deserialize($response, '\Infoplus\Model\Vendor', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Infoplus\ObjectSerializer::deserialize($e->getResponseBody(), '\Infoplus\Model\Vendor', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getVendorByFilter
     *
     * Search vendors by filter
     *
     * @param string $filter Query string, used to filter results. (optional)
     * @param int $page Result page number.  Defaults to 1. (optional)
     * @param int $limit Maximum results per page.  Defaults to 20.  Max allowed value is 250. (optional)
     * @param string $sort Sort results by specified field. (optional)
     * @return \Infoplus\Model\Vendor[]
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getVendorByFilter($filter = null, $page = null, $limit = null, $sort = null)
    {
        list($response, $statusCode, $httpHeader) = $this->getVendorByFilterWithHttpInfo ($filter, $page, $limit, $sort);
        return $response; 
    }


    /**
     * getVendorByFilterWithHttpInfo
     *
     * Search vendors by filter
     *
     * @param string $filter Query string, used to filter results. (optional)
     * @param int $page Result page number.  Defaults to 1. (optional)
     * @param int $limit Maximum results per page.  Defaults to 20.  Max allowed value is 250. (optional)
     * @param string $sort Sort results by specified field. (optional)
     * @return Array of \Infoplus\Model\Vendor[], HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getVendorByFilterWithHttpInfo($filter = null, $page = null, $limit = null, $sort = null)
    {
        
  
        // parse inputs
        $resourcePath = "/beta/vendor/search";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        // query params
        
        if ($filter !== null) {
            $queryParams['filter'] = $this->apiClient->getSerializer()->toQueryValue($filter);
        }// query params
        
        if ($page !== null) {
            $queryParams['page'] = $this->apiClient->getSerializer()->toQueryValue($page);
        }// query params
        
        if ($limit !== null) {
            $queryParams['limit'] = $this->apiClient->getSerializer()->toQueryValue($limit);
        }// query params
        
        if ($sort !== null) {
            $queryParams['sort'] = $this->apiClient->getSerializer()->toQueryValue($sort);
        }
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams, '\Infoplus\Model\Vendor[]'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Infoplus\ObjectSerializer::deserialize($response, '\Infoplus\Model\Vendor[]', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Infoplus\ObjectSerializer::deserialize($e->getResponseBody(), '\Infoplus\Model\Vendor[]', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getVendorById
     *
     * Get a vendor by id
     *
     * @param int $vendor_id Id of the vendor to be returned. (required)
     * @return \Infoplus\Model\Vendor
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getVendorById($vendor_id)
    {
        list($response, $statusCode, $httpHeader) = $this->getVendorByIdWithHttpInfo ($vendor_id);
        return $response; 
    }


    /**
     * getVendorByIdWithHttpInfo
     *
     * Get a vendor by id
     *
     * @param int $vendor_id Id of the vendor to be returned. (required)
     * @return Array of \Infoplus\Model\Vendor, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getVendorByIdWithHttpInfo($vendor_id)
    {
        
        // verify the required parameter 'vendor_id' is set
        if ($vendor_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $vendor_id when calling getVendorById');
        }
  
        // parse inputs
        $resourcePath = "/beta/vendor/{vendorId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($vendor_id !== null) {
            $resourcePath = str_replace(
                "{" . "vendorId" . "}",
                $this->apiClient->getSerializer()->toPathValue($vendor_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams, '\Infoplus\Model\Vendor'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Infoplus\ObjectSerializer::deserialize($response, '\Infoplus\Model\Vendor', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Infoplus\ObjectSerializer::deserialize($e->getResponseBody(), '\Infoplus\Model\Vendor', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getVendorTags
     *
     * Get the tags for a vendor.
     *
     * @param int $vendor_id Id of the vendor to get tags for (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getVendorTags($vendor_id)
    {
        list($response, $statusCode, $httpHeader) = $this->getVendorTagsWithHttpInfo ($vendor_id);
        return $response; 
    }


    /**
     * getVendorTagsWithHttpInfo
     *
     * Get the tags for a vendor.
     *
     * @param int $vendor_id Id of the vendor to get tags for (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function getVendorTagsWithHttpInfo($vendor_id)
    {
        
        // verify the required parameter 'vendor_id' is set
        if ($vendor_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $vendor_id when calling getVendorTags');
        }
  
        // parse inputs
        $resourcePath = "/beta/vendor/{vendorId}/tag";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($vendor_id !== null) {
            $resourcePath = str_replace(
                "{" . "vendorId" . "}",
                $this->apiClient->getSerializer()->toPathValue($vendor_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * updateVendor
     *
     * Update a vendor
     *
     * @param \Infoplus\Model\Vendor $body Vendor to be updated. (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function updateVendor($body)
    {
        list($response, $statusCode, $httpHeader) = $this->updateVendorWithHttpInfo ($body);
        return $response; 
    }


    /**
     * updateVendorWithHttpInfo
     *
     * Update a vendor
     *
     * @param \Infoplus\Model\Vendor $body Vendor to be updated. (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function updateVendorWithHttpInfo($body)
    {
        
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling updateVendor');
        }
  
        // parse inputs
        $resourcePath = "/beta/vendor";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'PUT',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * updateVendorCustomFields
     *
     * Update a vendor custom fields
     *
     * @param \Infoplus\Model\Vendor $body Vendor to be updated. (required)
     * @return void
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function updateVendorCustomFields($body)
    {
        list($response, $statusCode, $httpHeader) = $this->updateVendorCustomFieldsWithHttpInfo ($body);
        return $response; 
    }


    /**
     * updateVendorCustomFieldsWithHttpInfo
     *
     * Update a vendor custom fields
     *
     * @param \Infoplus\Model\Vendor $body Vendor to be updated. (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Infoplus\ApiException on non-2xx response
     */
    public function updateVendorCustomFieldsWithHttpInfo($body)
    {
        
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling updateVendorCustomFields');
        }
  
        // parse inputs
        $resourcePath = "/beta/vendor/customFields";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('API-Key');
        if (strlen($apiKey) !== 0) {
            $headerParams['API-Key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'PUT',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
}
