<?php
/**
 * BusinessTransactionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Infoplus;

use \Infoplus\Configuration;
use \Infoplus\ApiException;
use \Infoplus\ObjectSerializer;

/**
 * BusinessTransactionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Infoplus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BusinessTransactionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addBusinessTransaction
     *
     * Create a businessTransaction.
     *
     */
    public function testAddBusinessTransaction()
    {
    }

    /**
     * Test case for addBusinessTransactionAudit
     *
     * Add new audit for a businessTransaction.
     *
     */
    public function testAddBusinessTransactionAudit()
    {
    }

    /**
     * Test case for addBusinessTransactionFile
     *
     * Attach a file to a businessTransaction.
     *
     */
    public function testAddBusinessTransactionFile()
    {
    }

    /**
     * Test case for addBusinessTransactionFileByURL
     *
     * Attach a file to a businessTransaction by URL..
     *
     */
    public function testAddBusinessTransactionFileByURL()
    {
    }

    /**
     * Test case for addBusinessTransactionTag
     *
     * Add new tags for a businessTransaction..
     *
     */
    public function testAddBusinessTransactionTag()
    {
    }

    /**
     * Test case for deleteBusinessTransactionFile
     *
     * Delete a file for a businessTransaction..
     *
     */
    public function testDeleteBusinessTransactionFile()
    {
    }

    /**
     * Test case for deleteBusinessTransactionTag
     *
     * Delete a tag for a businessTransaction..
     *
     */
    public function testDeleteBusinessTransactionTag()
    {
    }

    /**
     * Test case for getBusinessTransactionByFilter
     *
     * Search businessTransactions by filter.
     *
     */
    public function testGetBusinessTransactionByFilter()
    {
    }

    /**
     * Test case for getBusinessTransactionById
     *
     * Get a businessTransaction by id.
     *
     */
    public function testGetBusinessTransactionById()
    {
    }

    /**
     * Test case for getBusinessTransactionFiles
     *
     * Get the files for a businessTransaction..
     *
     */
    public function testGetBusinessTransactionFiles()
    {
    }

    /**
     * Test case for getBusinessTransactionTags
     *
     * Get the tags for a businessTransaction..
     *
     */
    public function testGetBusinessTransactionTags()
    {
    }

    /**
     * Test case for getDuplicateBusinessTransactionById
     *
     * Get a duplicated a businessTransaction by id.
     *
     */
    public function testGetDuplicateBusinessTransactionById()
    {
    }

    /**
     * Test case for updateBusinessTransaction
     *
     * Update a businessTransaction.
     *
     */
    public function testUpdateBusinessTransaction()
    {
    }

    /**
     * Test case for updateBusinessTransactionCustomFields
     *
     * Update a businessTransaction custom fields.
     *
     */
    public function testUpdateBusinessTransactionCustomFields()
    {
    }
}
