<?php
/**
 * CartonTypeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Infoplus;

use \Infoplus\Configuration;
use \Infoplus\ApiException;
use \Infoplus\ObjectSerializer;

/**
 * CartonTypeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Infoplus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CartonTypeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addCartonType
     *
     * Create a cartonType.
     *
     */
    public function testAddCartonType()
    {
    }

    /**
     * Test case for addCartonTypeAudit
     *
     * Add new audit for a cartonType.
     *
     */
    public function testAddCartonTypeAudit()
    {
    }

    /**
     * Test case for addCartonTypeFile
     *
     * Attach a file to a cartonType.
     *
     */
    public function testAddCartonTypeFile()
    {
    }

    /**
     * Test case for addCartonTypeFileByURL
     *
     * Attach a file to a cartonType by URL..
     *
     */
    public function testAddCartonTypeFileByURL()
    {
    }

    /**
     * Test case for addCartonTypeTag
     *
     * Add new tags for a cartonType..
     *
     */
    public function testAddCartonTypeTag()
    {
    }

    /**
     * Test case for deleteCartonType
     *
     * Delete a cartonType.
     *
     */
    public function testDeleteCartonType()
    {
    }

    /**
     * Test case for deleteCartonTypeFile
     *
     * Delete a file for a cartonType..
     *
     */
    public function testDeleteCartonTypeFile()
    {
    }

    /**
     * Test case for deleteCartonTypeTag
     *
     * Delete a tag for a cartonType..
     *
     */
    public function testDeleteCartonTypeTag()
    {
    }

    /**
     * Test case for getCartonTypeByFilter
     *
     * Search cartonTypes by filter.
     *
     */
    public function testGetCartonTypeByFilter()
    {
    }

    /**
     * Test case for getCartonTypeById
     *
     * Get a cartonType by id.
     *
     */
    public function testGetCartonTypeById()
    {
    }

    /**
     * Test case for getCartonTypeFiles
     *
     * Get the files for a cartonType..
     *
     */
    public function testGetCartonTypeFiles()
    {
    }

    /**
     * Test case for getCartonTypeTags
     *
     * Get the tags for a cartonType..
     *
     */
    public function testGetCartonTypeTags()
    {
    }

    /**
     * Test case for getDuplicateCartonTypeById
     *
     * Get a duplicated a cartonType by id.
     *
     */
    public function testGetDuplicateCartonTypeById()
    {
    }

    /**
     * Test case for updateCartonType
     *
     * Update a cartonType.
     *
     */
    public function testUpdateCartonType()
    {
    }

    /**
     * Test case for updateCartonTypeCustomFields
     *
     * Update a cartonType custom fields.
     *
     */
    public function testUpdateCartonTypeCustomFields()
    {
    }
}
