<?php
/**
 * CartonContentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Infoplus;

use \Infoplus\Configuration;
use \Infoplus\ApiException;
use \Infoplus\ObjectSerializer;

/**
 * CartonContentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Infoplus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CartonContentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addCartonContent
     *
     * Create a cartonContent.
     *
     */
    public function testAddCartonContent()
    {
    }

    /**
     * Test case for addCartonContentAudit
     *
     * Add new audit for a cartonContent.
     *
     */
    public function testAddCartonContentAudit()
    {
    }

    /**
     * Test case for addCartonContentFile
     *
     * Attach a file to a cartonContent.
     *
     */
    public function testAddCartonContentFile()
    {
    }

    /**
     * Test case for addCartonContentFileByURL
     *
     * Attach a file to a cartonContent by URL..
     *
     */
    public function testAddCartonContentFileByURL()
    {
    }

    /**
     * Test case for addCartonContentTag
     *
     * Add new tags for a cartonContent..
     *
     */
    public function testAddCartonContentTag()
    {
    }

    /**
     * Test case for deleteCartonContent
     *
     * Delete a cartonContent.
     *
     */
    public function testDeleteCartonContent()
    {
    }

    /**
     * Test case for deleteCartonContentFile
     *
     * Delete a file for a cartonContent..
     *
     */
    public function testDeleteCartonContentFile()
    {
    }

    /**
     * Test case for deleteCartonContentTag
     *
     * Delete a tag for a cartonContent..
     *
     */
    public function testDeleteCartonContentTag()
    {
    }

    /**
     * Test case for getCartonContentByFilter
     *
     * Search cartonContents by filter.
     *
     */
    public function testGetCartonContentByFilter()
    {
    }

    /**
     * Test case for getCartonContentById
     *
     * Get a cartonContent by id.
     *
     */
    public function testGetCartonContentById()
    {
    }

    /**
     * Test case for getCartonContentFiles
     *
     * Get the files for a cartonContent..
     *
     */
    public function testGetCartonContentFiles()
    {
    }

    /**
     * Test case for getCartonContentTags
     *
     * Get the tags for a cartonContent..
     *
     */
    public function testGetCartonContentTags()
    {
    }

    /**
     * Test case for getDuplicateCartonContentById
     *
     * Get a duplicated a cartonContent by id.
     *
     */
    public function testGetDuplicateCartonContentById()
    {
    }

    /**
     * Test case for updateCartonContent
     *
     * Update a cartonContent.
     *
     */
    public function testUpdateCartonContent()
    {
    }

    /**
     * Test case for updateCartonContentCustomFields
     *
     * Update a cartonContent custom fields.
     *
     */
    public function testUpdateCartonContentCustomFields()
    {
    }
}
