<?php
/**
 * CustomFieldApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Infoplus;

use \Infoplus\Configuration;
use \Infoplus\ApiException;
use \Infoplus\ObjectSerializer;

/**
 * CustomFieldApiTest Class Doc Comment
 *
 * @category Class
 * @package  Infoplus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomFieldApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addCustomField
     *
     * Create a customField.
     *
     */
    public function testAddCustomField()
    {
    }

    /**
     * Test case for addCustomFieldAudit
     *
     * Add new audit for a customField.
     *
     */
    public function testAddCustomFieldAudit()
    {
    }

    /**
     * Test case for addCustomFieldFile
     *
     * Attach a file to a customField.
     *
     */
    public function testAddCustomFieldFile()
    {
    }

    /**
     * Test case for addCustomFieldFileByURL
     *
     * Attach a file to a customField by URL..
     *
     */
    public function testAddCustomFieldFileByURL()
    {
    }

    /**
     * Test case for addCustomFieldTag
     *
     * Add new tags for a customField..
     *
     */
    public function testAddCustomFieldTag()
    {
    }

    /**
     * Test case for deleteCustomFieldFile
     *
     * Delete a file for a customField..
     *
     */
    public function testDeleteCustomFieldFile()
    {
    }

    /**
     * Test case for deleteCustomFieldTag
     *
     * Delete a tag for a customField..
     *
     */
    public function testDeleteCustomFieldTag()
    {
    }

    /**
     * Test case for getCustomFieldByFilter
     *
     * Search customFields by filter.
     *
     */
    public function testGetCustomFieldByFilter()
    {
    }

    /**
     * Test case for getCustomFieldById
     *
     * Get a customField by id.
     *
     */
    public function testGetCustomFieldById()
    {
    }

    /**
     * Test case for getCustomFieldFiles
     *
     * Get the files for a customField..
     *
     */
    public function testGetCustomFieldFiles()
    {
    }

    /**
     * Test case for getCustomFieldTags
     *
     * Get the tags for a customField..
     *
     */
    public function testGetCustomFieldTags()
    {
    }

    /**
     * Test case for getDuplicateCustomFieldById
     *
     * Get a duplicated a customField by id.
     *
     */
    public function testGetDuplicateCustomFieldById()
    {
    }

    /**
     * Test case for updateCustomField
     *
     * Update a customField.
     *
     */
    public function testUpdateCustomField()
    {
    }
}
