<?php
/**
 * FulfillmentProcessLogApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Infoplus;

use \Infoplus\Configuration;
use \Infoplus\ApiException;
use \Infoplus\ObjectSerializer;

/**
 * FulfillmentProcessLogApiTest Class Doc Comment
 *
 * @category Class
 * @package  Infoplus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FulfillmentProcessLogApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addFulfillmentProcessLogAudit
     *
     * Add new audit for a fulfillmentProcessLog.
     *
     */
    public function testAddFulfillmentProcessLogAudit()
    {
    }

    /**
     * Test case for addFulfillmentProcessLogFile
     *
     * Attach a file to a fulfillmentProcessLog.
     *
     */
    public function testAddFulfillmentProcessLogFile()
    {
    }

    /**
     * Test case for addFulfillmentProcessLogFileByURL
     *
     * Attach a file to a fulfillmentProcessLog by URL..
     *
     */
    public function testAddFulfillmentProcessLogFileByURL()
    {
    }

    /**
     * Test case for addFulfillmentProcessLogTag
     *
     * Add new tags for a fulfillmentProcessLog..
     *
     */
    public function testAddFulfillmentProcessLogTag()
    {
    }

    /**
     * Test case for deleteFulfillmentProcessLogFile
     *
     * Delete a file for a fulfillmentProcessLog..
     *
     */
    public function testDeleteFulfillmentProcessLogFile()
    {
    }

    /**
     * Test case for deleteFulfillmentProcessLogTag
     *
     * Delete a tag for a fulfillmentProcessLog..
     *
     */
    public function testDeleteFulfillmentProcessLogTag()
    {
    }

    /**
     * Test case for getDuplicateFulfillmentProcessLogById
     *
     * Get a duplicated a fulfillmentProcessLog by id.
     *
     */
    public function testGetDuplicateFulfillmentProcessLogById()
    {
    }

    /**
     * Test case for getFulfillmentProcessLogByFilter
     *
     * Search fulfillmentProcessLogs by filter.
     *
     */
    public function testGetFulfillmentProcessLogByFilter()
    {
    }

    /**
     * Test case for getFulfillmentProcessLogById
     *
     * Get a fulfillmentProcessLog by id.
     *
     */
    public function testGetFulfillmentProcessLogById()
    {
    }

    /**
     * Test case for getFulfillmentProcessLogFiles
     *
     * Get the files for a fulfillmentProcessLog..
     *
     */
    public function testGetFulfillmentProcessLogFiles()
    {
    }

    /**
     * Test case for getFulfillmentProcessLogTags
     *
     * Get the tags for a fulfillmentProcessLog..
     *
     */
    public function testGetFulfillmentProcessLogTags()
    {
    }
}
