<?php
/**
 * LoadApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Infoplus;

use \Infoplus\Configuration;
use \Infoplus\ApiException;
use \Infoplus\ObjectSerializer;

/**
 * LoadApiTest Class Doc Comment
 *
 * @category Class
 * @package  Infoplus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LoadApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addLoadAudit
     *
     * Add new audit for a load.
     *
     */
    public function testAddLoadAudit()
    {
    }

    /**
     * Test case for addLoadFile
     *
     * Attach a file to a load.
     *
     */
    public function testAddLoadFile()
    {
    }

    /**
     * Test case for addLoadFileByURL
     *
     * Attach a file to a load by URL..
     *
     */
    public function testAddLoadFileByURL()
    {
    }

    /**
     * Test case for addLoadTag
     *
     * Add new tags for a load..
     *
     */
    public function testAddLoadTag()
    {
    }

    /**
     * Test case for deleteLoadFile
     *
     * Delete a file for a load..
     *
     */
    public function testDeleteLoadFile()
    {
    }

    /**
     * Test case for deleteLoadTag
     *
     * Delete a tag for a load..
     *
     */
    public function testDeleteLoadTag()
    {
    }

    /**
     * Test case for getDuplicateLoadById
     *
     * Get a duplicated a load by id.
     *
     */
    public function testGetDuplicateLoadById()
    {
    }

    /**
     * Test case for getLoadByFilter
     *
     * Search loads by filter.
     *
     */
    public function testGetLoadByFilter()
    {
    }

    /**
     * Test case for getLoadById
     *
     * Get a load by id.
     *
     */
    public function testGetLoadById()
    {
    }

    /**
     * Test case for getLoadFiles
     *
     * Get the files for a load..
     *
     */
    public function testGetLoadFiles()
    {
    }

    /**
     * Test case for getLoadTags
     *
     * Get the tags for a load..
     *
     */
    public function testGetLoadTags()
    {
    }

    /**
     * Test case for updateLoadCustomFields
     *
     * Update a load custom fields.
     *
     */
    public function testUpdateLoadCustomFields()
    {
    }
}
