<?php
/**
 * ReturnOrderApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Infoplus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Infoplus;

use \Infoplus\Configuration;
use \Infoplus\ApiException;
use \Infoplus\ObjectSerializer;

/**
 * ReturnOrderApiTest Class Doc Comment
 *
 * @category Class
 * @package  Infoplus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReturnOrderApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addReturnOrderAudit
     *
     * Add new audit for a returnOrder.
     *
     */
    public function testAddReturnOrderAudit()
    {
    }

    /**
     * Test case for addReturnOrderFile
     *
     * Attach a file to a returnOrder.
     *
     */
    public function testAddReturnOrderFile()
    {
    }

    /**
     * Test case for addReturnOrderFileByURL
     *
     * Attach a file to a returnOrder by URL..
     *
     */
    public function testAddReturnOrderFileByURL()
    {
    }

    /**
     * Test case for addReturnOrderTag
     *
     * Add new tags for a returnOrder..
     *
     */
    public function testAddReturnOrderTag()
    {
    }

    /**
     * Test case for deleteReturnOrderFile
     *
     * Delete a file for a returnOrder..
     *
     */
    public function testDeleteReturnOrderFile()
    {
    }

    /**
     * Test case for deleteReturnOrderTag
     *
     * Delete a tag for a returnOrder..
     *
     */
    public function testDeleteReturnOrderTag()
    {
    }

    /**
     * Test case for getDuplicateReturnOrderById
     *
     * Get a duplicated a returnOrder by id.
     *
     */
    public function testGetDuplicateReturnOrderById()
    {
    }

    /**
     * Test case for getReturnOrderByFilter
     *
     * Search returnOrders by filter.
     *
     */
    public function testGetReturnOrderByFilter()
    {
    }

    /**
     * Test case for getReturnOrderById
     *
     * Get a returnOrder by id.
     *
     */
    public function testGetReturnOrderById()
    {
    }

    /**
     * Test case for getReturnOrderFiles
     *
     * Get the files for a returnOrder..
     *
     */
    public function testGetReturnOrderFiles()
    {
    }

    /**
     * Test case for getReturnOrderTags
     *
     * Get the tags for a returnOrder..
     *
     */
    public function testGetReturnOrderTags()
    {
    }

    /**
     * Test case for updateReturnOrder
     *
     * Update a returnOrder.
     *
     */
    public function testUpdateReturnOrder()
    {
    }

    /**
     * Test case for updateReturnOrderCustomFields
     *
     * Update a returnOrder custom fields.
     *
     */
    public function testUpdateReturnOrderCustomFields()
    {
    }
}
